-- 00016_style_match.sql
-- Play Style Match: NBA player style profiles (read-only) and each player's saved
-- match results. The player list is added at the end. Safe to re-run.

CREATE TABLE IF NOT EXISTS public.nba_players (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  slug text UNIQUE NOT NULL,
  name text NOT NULL,
  era text NOT NULL CHECK (era IN ('modern', 'legend')),
  position text NOT NULL CHECK (position IN ('PG', 'SG', 'SF', 'PF', 'C')),
  height_cm smallint NOT NULL CHECK (height_cm BETWEEN 150 AND 240),
  archetype text NOT NULL,
  style_tags text[] NOT NULL DEFAULT '{}',
  shot_profile jsonb NOT NULL,
  strengths text[] NOT NULL DEFAULT '{}',
  signature_moves text[] NOT NULL DEFAULT '{}',
  how_to_copy text[] NOT NULL DEFAULT '{}',
  drill_skills text[] NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS public.style_match_results (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  source text NOT NULL DEFAULT 'profile' CHECK (source IN ('profile', 'video')),
  input jsonb NOT NULL,
  matches jsonb NOT NULL,
  report jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_style_match_results_user ON public.style_match_results(user_id, created_at DESC);

ALTER TABLE public.nba_players ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.style_match_results ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Players can view NBA style profiles" ON public.nba_players;
CREATE POLICY "Players can view NBA style profiles" ON public.nba_players FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "Users view own style matches" ON public.style_match_results;
CREATE POLICY "Users view own style matches" ON public.style_match_results FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users save own style matches" ON public.style_match_results;
CREATE POLICY "Users save own style matches" ON public.style_match_results FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users delete own style matches" ON public.style_match_results;
CREATE POLICY "Users delete own style matches" ON public.style_match_results FOR DELETE USING (auth.uid() = user_id);

GRANT SELECT ON public.nba_players TO authenticated;
GRANT SELECT, INSERT, DELETE ON public.style_match_results TO authenticated;
GRANT ALL ON public.nba_players, public.style_match_results TO service_role;
REVOKE ALL ON public.nba_players, public.style_match_results FROM anon;

-- =============================================================================
-- NBA PLAYER STYLE PROFILES
-- =============================================================================
-- HoopIQ Play Style Match: NBA player comparison dataset (104 players)
-- Heights are commonly listed heights converted to cm (1 in = 2.54 cm, rounded).
-- shot_profile values are rough prime-era shares of shot attempts by distance.
-- Safe to re-run: existing slugs are skipped.
INSERT INTO public.nba_players (slug, name, era, position, height_cm, archetype, style_tags, shot_profile, strengths, signature_moves, how_to_copy, drill_skills) VALUES
('stephen-curry', 'Stephen Curry', 'modern', 'PG', 188, 'Sharpshooter', ARRAY['movement_shooter','pick_and_roll_handler','spot_up_shooter','transition_threat'], '{"rim":0.22,"mid":0.10,"three":0.68}'::jsonb, ARRAY['Deep-range pull-up shooting','Constant off-ball movement','Quick, compact release'], ARRAY['Transition pull-up three','Off-ball relocation three','Behind-the-back into step-back three'], ARRAY['Groove a quick one-motion release close to the rim, then step back one foot at a time','After you pass, sprint to a new open spot instead of standing still','Do two-ball dribbling drills daily so your handle holds up on pull-ups'], ARRAY['shooting','ball_handling','conditioning']),
('chris-paul', 'Chris Paul', 'modern', 'PG', 183, 'Floor General', ARRAY['pick_and_roll_handler','floor_general','mid_range_scorer','point_of_attack_defender'], '{"rim":0.20,"mid":0.45,"three":0.35}'::jsonb, ARRAY['Elite pick-and-roll control','Low-turnover decision making','Reliable elbow jumper'], ARRAY['Snake dribble into elbow pull-up','Hesitation into pocket pass','Rejecting the screen'], ARRAY['Use the snake dribble: come off the screen and cut back across it to keep your defender on your hip','Practise the 15-foot pull-up from both elbows until it is automatic','Track assists and turnovers each game and aim for three assists per turnover'], ARRAY['passing','ball_handling','shooting']),
('damian-lillard', 'Damian Lillard', 'modern', 'PG', 188, 'Scoring Guard', ARRAY['pick_and_roll_handler','isolation_scorer','transition_threat'], '{"rim":0.30,"mid":0.10,"three":0.60}'::jsonb, ARRAY['Very deep pull-up range','Composure late in games','Strong downhill drives'], ARRAY['Deep pull-up three','Step-back three','Hesitation drive'], ARRAY['Extend range gradually: only move back once you make 7 of 10 from your current spot','Use a hesitation dribble to freeze your defender before attacking','End workouts with pressure shots, like needing three makes in a row to finish'], ARRAY['shooting','ball_handling']),
('kyrie-irving', 'Kyrie Irving', 'modern', 'PG', 188, 'Scoring Guard', ARRAY['isolation_scorer','pick_and_roll_handler','mid_range_scorer'], '{"rim":0.35,"mid":0.30,"three":0.35}'::jsonb, ARRAY['Creative ball handling','Finishing with either hand','Tough shot-making'], ARRAY['Spin-move layup off the glass','Crossover into hesitation','Reverse layup under the rim'], ARRAY['Do stationary and moving dribble combos with both hands every day','Practise layups off high glass angles with your weak hand','Use Mikan and reverse-layup drills to learn to finish around shot blockers'], ARRAY['ball_handling','finishing']),
('trae-young', 'Trae Young', 'modern', 'PG', 185, 'Floor General', ARRAY['pick_and_roll_handler','playmaker','floor_general','isolation_scorer'], '{"rim":0.30,"mid":0.20,"three":0.50}'::jsonb, ARRAY['Lob and skip-pass vision','Deep pull-up shooting','Floater touch in the lane'], ARRAY['Floater over the big','Pick-and-roll lob pass','Deep pull-up three'], ARRAY['Practise floaters from 6 to 10 feet with a soft, high arc','In pick-and-roll, read the big: if he drops, shoot or float; if he jumps out, throw the lob or pocket pass','Work on one-handed passes off the dribble with both hands'], ARRAY['passing','shooting','ball_handling']),
('ja-morant', 'Ja Morant', 'modern', 'PG', 188, 'Slasher', ARRAY['slasher','pick_and_roll_handler','transition_threat','playmaker'], '{"rim":0.60,"mid":0.15,"three":0.25}'::jsonb, ARRAY['Explosive first step','Acrobatic finishing','Speed in transition'], ARRAY['Euro step through traffic','Hang-dribble into burst','Two-foot jump-stop finish'], ARRAY['Practise euro steps and jump stops at game speed so you can finish around bigger players','Build explosive power with box jumps and bounds, with proper rest','Push the ball up the floor after every defensive rebound to find early scoring chances'], ARRAY['finishing','conditioning','ball_handling']),
('kyle-lowry', 'Kyle Lowry', 'modern', 'PG', 183, 'Combo Guard', ARRAY['pick_and_roll_handler','connector','point_of_attack_defender','spot_up_shooter'], '{"rim":0.30,"mid":0.15,"three":0.55}'::jsonb, ARRAY['Taking charges and hustle plays','Pull-up and spot-up threes','Quick outlet passing'], ARRAY['Drawing the charge','Transition pull-up three','Hit-ahead outlet pass'], ARRAY['Practise sliding in front of a driver and setting your feet early to take a legal charge','Throw the outlet pass right after a rebound to start the fast break','Stay low and strong with the ball to hold off bigger defenders'], ARRAY['defense','passing','shooting']),
('jalen-brunson', 'Jalen Brunson', 'modern', 'PG', 188, 'Scoring Guard', ARRAY['isolation_scorer','pick_and_roll_handler','mid_range_scorer','post_scorer'], '{"rim":0.35,"mid":0.35,"three":0.30}'::jsonb, ARRAY['Elite footwork and pivots','Change of pace','Guard post-ups'], ARRAY['Up-and-under pivot','Shoulder-fake fadeaway','Hesitation into jump stop'], ARRAY['Master pivots: jump stop, then practise front and reverse pivots with shot fakes','Change speeds on drives: slow, slow, then burst','Post up smaller guards and use shoulder fakes before you shoot'], ARRAY['footwork','finishing','shooting']),
('fred-vanvleet', 'Fred VanVleet', 'modern', 'PG', 183, 'Combo Guard', ARRAY['spot_up_shooter','pick_and_roll_handler','point_of_attack_defender','connector'], '{"rim":0.25,"mid":0.10,"three":0.65}'::jsonb, ARRAY['Pull-up threes off screens','Active hands on defense','Low-mistake playmaking'], ARRAY['Pull-up three when the defender goes under','Digging for steals on drives','Hesitation step-back'], ARRAY['Practise pull-up threes coming off a screen when your defender goes under it','Keep your hands active in passing lanes during defensive drills','Play under control and aim for more assists than turnovers every game'], ARRAY['shooting','defense']),
('mike-conley', 'Mike Conley', 'modern', 'PG', 185, 'Floor General', ARRAY['pick_and_roll_handler','floor_general','mid_range_scorer','point_of_attack_defender'], '{"rim":0.30,"mid":0.30,"three":0.40}'::jsonb, ARRAY['Steady control of tempo','Floaters and runners','Smart team defense'], ARRAY['Left-handed floater','Pick-and-roll pocket pass','Pull-up runner'], ARRAY['Practise floaters with both hands from different angles in the lane','Keep your dribble alive under pressure until a teammate comes open','Guard the ball by moving your feet instead of reaching'], ARRAY['finishing','passing','defense']),
('kemba-walker', 'Kemba Walker', 'modern', 'PG', 183, 'Scoring Guard', ARRAY['isolation_scorer','pick_and_roll_handler','transition_threat'], '{"rim":0.30,"mid":0.25,"three":0.45}'::jsonb, ARRAY['Quick crossover','Step-back jumper','Speed in the open floor'], ARRAY['Crossover step-back','Splitting the pick-and-roll','Stop-and-pop pull-up'], ARRAY['Practise crossovers low and quick, keeping the ball below your knees','Work on step-back jumpers going both left and right','Split two defenders on a screen with a low, quick dribble'], ARRAY['ball_handling','shooting']),
('isaiah-thomas', 'Isaiah Thomas', 'modern', 'PG', 175, 'Scoring Guard', ARRAY['isolation_scorer','pick_and_roll_handler','slasher'], '{"rim":0.45,"mid":0.15,"three":0.40}'::jsonb, ARRAY['Crafty finishing among bigs','Low center of gravity','Fourth-quarter scoring'], ARRAY['Wrong-foot layup','Up-and-under at the rim','Pull-up three off the screen'], ARRAY['Practise finishing off the wrong foot to throw off shot blockers','Use angles and the backboard to score over taller defenders','Dribble low so bigger players struggle to reach the ball'], ARRAY['finishing','ball_handling']),
('tyrese-maxey', 'Tyrese Maxey', 'modern', 'PG', 188, 'Combo Guard', ARRAY['transition_threat','slasher','spot_up_shooter','pick_and_roll_handler'], '{"rim":0.35,"mid":0.20,"three":0.45}'::jsonb, ARRAY['End-to-end speed','Reliable three-point range','Soft floater'], ARRAY['Coast-to-coast layup','Floater in the lane','Transition pull-up three'], ARRAY['Sprint the ball up after rebounds and attack before the defense sets','Practise floaters from the lane at full speed','Build range with 100-shot three-point sessions and log your makes'], ARRAY['conditioning','finishing','shooting']),
('darius-garland', 'Darius Garland', 'modern', 'PG', 185, 'Combo Guard', ARRAY['pick_and_roll_handler','playmaker','mid_range_scorer','spot_up_shooter'], '{"rim":0.30,"mid":0.30,"three":0.40}'::jsonb, ARRAY['Shifty ball handling','Creative passing','Floaters and pull-ups'], ARRAY['Behind-the-back crossover','Wraparound pass','Short floater'], ARRAY['Practise dribble combos that change direction fast, like between-the-legs into behind-the-back','Work on passing with either hand around a defender','Develop a floater for when the big protects the rim'], ARRAY['ball_handling','passing']),
('donovan-mitchell', 'Donovan Mitchell', 'modern', 'SG', 185, 'Scoring Guard', ARRAY['isolation_scorer','pick_and_roll_handler','slasher'], '{"rim":0.35,"mid":0.20,"three":0.45}'::jsonb, ARRAY['Explosive athleticism','Step-back three','Finishing through contact'], ARRAY['Step-back three','Explosive drive and dunk','Hesitation pull-up'], ARRAY['Practise step-back jumpers from the wing and top of the key','Have a partner bump you with a pad while you finish layups','Train your first step with short sprints and quick-start drills'], ARRAY['shooting','finishing','conditioning']),
('russell-westbrook', 'Russell Westbrook', 'modern', 'PG', 191, 'Slasher', ARRAY['slasher','transition_threat','rebounder','playmaker'], '{"rim":0.50,"mid":0.30,"three":0.20}'::jsonb, ARRAY['Relentless energy','Rebounding as a guard','Downhill speed'], ARRAY['Rebound and push fast break','Quick-stop mid-range pull-up','Drive and kick-out'], ARRAY['Crash the defensive glass as a guard and push the ball right away','Build conditioning with sprint intervals so you can play hard every possession','Practise a quick-stop pull-up at the elbow for when the lane is closed'], ARRAY['conditioning','rebounding','finishing']),
('deaaron-fox', 'De''Aaron Fox', 'modern', 'PG', 191, 'Slasher', ARRAY['slasher','transition_threat','pick_and_roll_handler','point_of_attack_defender'], '{"rim":0.50,"mid":0.25,"three":0.25}'::jsonb, ARRAY['Elite straight-line speed','Late-game shot-making','Quick hands on defense'], ARRAY['Speed layup in transition','Hesitation into burst','Floater off the drive'], ARRAY['Race the ball up the court and attack before defenders get set','Practise full-speed layups with both hands','Use a hesitation dribble to set up your drive'], ARRAY['finishing','conditioning','ball_handling']),
('jrue-holiday', 'Jrue Holiday', 'modern', 'PG', 193, 'Combo Guard', ARRAY['point_of_attack_defender','two_way','connector','spot_up_shooter'], '{"rim":0.30,"mid":0.30,"three":0.40}'::jsonb, ARRAY['Elite on-ball defense','Strong frame for a guard','Unselfish decision making'], ARRAY['Strip on the drive','Chase-down block','Mid-range pull-up'], ARRAY['Do defensive slide drills daily, staying low with active hands','Pick up the ball handler early and make every dribble difficult','Practise catch-and-shoot threes so you stay useful off the ball'], ARRAY['defense','shooting']),
('james-harden', 'James Harden', 'modern', 'SG', 196, 'Scoring Guard', ARRAY['isolation_scorer','pick_and_roll_handler','playmaker'], '{"rim":0.40,"mid":0.05,"three":0.55}'::jsonb, ARRAY['Step-back three','Drawing fouls on drives','Pick-and-roll passing'], ARRAY['Step-back three','Euro step','Lob to the rolling big'], ARRAY['Practise the step-back from a slow dribble, landing balanced','Use the euro step to slip past shot blockers','Master the lob pass to a rolling teammate in two-man drills'], ARRAY['shooting','ball_handling','passing']),
('luka-doncic', 'Luka Doncic', 'modern', 'PG', 201, 'Floor General', ARRAY['pick_and_roll_handler','playmaker','isolation_scorer','rebounder'], '{"rim":0.35,"mid":0.20,"three":0.45}'::jsonb, ARRAY['Change-of-pace control','Elite passing vision','Step-back shooting'], ARRAY['Step-back three','Guard post-up','Cross-court skip pass'], ARRAY['Play at your own speed: slow down, then accelerate to beat your defender','Practise skip passes across the court to the weak-side shooter','Use your body to shield the defender on drives'], ARRAY['passing','shooting','ball_handling']),
('shai-gilgeous-alexander', 'Shai Gilgeous-Alexander', 'modern', 'PG', 198, 'Scoring Guard', ARRAY['isolation_scorer','slasher','mid_range_scorer','pick_and_roll_handler'], '{"rim":0.45,"mid":0.35,"three":0.20}'::jsonb, ARRAY['Herky-jerky change of pace','Elite mid-range scoring','Drawing contact at the rim'], ARRAY['Hesitation drive','Mid-range pull-up','Long-stride euro step'], ARRAY['Practise hesitation dribbles that change speed to throw off a defender''s balance','Build a reliable pull-up from 12 to 16 feet','Work on long, controlled strides into layups'], ARRAY['ball_handling','shooting','footwork']),
('devin-booker', 'Devin Booker', 'modern', 'SG', 196, 'Scoring Guard', ARRAY['mid_range_scorer','isolation_scorer','pick_and_roll_handler','movement_shooter'], '{"rim":0.25,"mid":0.40,"three":0.35}'::jsonb, ARRAY['Complete shooting package','Footwork and fakes','Scoring at all three levels'], ARRAY['Mid-range fadeaway','Jab-step jumper','Pull-up off the screen'], ARRAY['Shoot from every spot on the floor, inside and outside the arc','Use jab steps to create space before you shoot','Film your shot to keep your form consistent'], ARRAY['shooting','footwork']),
('klay-thompson', 'Klay Thompson', 'modern', 'SG', 198, 'Sharpshooter', ARRAY['movement_shooter','spot_up_shooter','perimeter_defender','two_way'], '{"rim":0.15,"mid":0.20,"three":0.65}'::jsonb, ARRAY['Lightning catch-and-shoot','Scoring on few dribbles','Perimeter defense'], ARRAY['Catch-and-shoot off a pin-down screen','Curl into mid-range jumper','Quick-release corner three'], ARRAY['Catch and shoot in one motion with your feet already set','Run off screens in drills and shoot immediately on the catch','Volunteer to guard the other team''s best shooter'], ARRAY['shooting','footwork','defense']),
('anthony-edwards', 'Anthony Edwards', 'modern', 'SG', 193, 'Scoring Guard', ARRAY['slasher','isolation_scorer','transition_threat','spot_up_shooter'], '{"rim":0.40,"mid":0.15,"three":0.45}'::jsonb, ARRAY['Explosive athleticism','Pull-up three','Powerful finishing'], ARRAY['Two-hand drive and dunk','Pull-up three','Spin move to the rim'], ARRAY['Build leg strength and explosiveness with squats and jumps','Attack the rim hard and practise finishing through contact','Work on pull-up threes off one or two dribbles'], ARRAY['finishing','shooting','conditioning']),
('tyrese-haliburton', 'Tyrese Haliburton', 'modern', 'PG', 196, 'Floor General', ARRAY['floor_general','playmaker','transition_threat','pick_and_roll_handler'], '{"rim":0.25,"mid":0.15,"three":0.60}'::jsonb, ARRAY['Elite passing vision','Very low turnovers','Quick-trigger threes'], ARRAY['Hit-ahead pass in transition','Quick pull-up three','Behind-the-back pass'], ARRAY['Look up the floor for the long pass before you dribble after a rebound','Practise one-handed passes to both sides','Make the simple read to keep turnovers low'], ARRAY['passing','shooting']),
('lamelo-ball', 'LaMelo Ball', 'modern', 'PG', 201, 'Floor General', ARRAY['playmaker','transition_threat','pick_and_roll_handler','rebounder'], '{"rim":0.30,"mid":0.10,"three":0.60}'::jsonb, ARRAY['Creative passing','Size at point guard','Deep shooting range'], ARRAY['One-handed full-court pass','Behind-the-back dribble','Deep pull-up three'], ARRAY['Practise leading outlet passes to a teammate on the run','Use your height to see over defenders when you pass','Work on pull-up threes from a step behind the arc'], ARRAY['passing','ball_handling','shooting']),
('jimmy-butler', 'Jimmy Butler', 'modern', 'SF', 201, 'Two-Way Wing', ARRAY['two_way','slasher','perimeter_defender','mid_range_scorer'], '{"rim":0.45,"mid":0.35,"three":0.20}'::jsonb, ARRAY['Drawing fouls','Physical defense','Mid-range footwork'], ARRAY['Up-and-under','Jab-step pull-up','Jump stop into shot fake'], ARRAY['Use pump fakes and jump stops to draw fouls','Defend with your chest and feet, not reaching hands','Shoot 50 free throws after every workout'], ARRAY['footwork','defense','finishing']),
('kawhi-leonard', 'Kawhi Leonard', 'modern', 'SF', 201, 'Two-Way Wing', ARRAY['two_way','perimeter_defender','mid_range_scorer','isolation_scorer'], '{"rim":0.25,"mid":0.40,"three":0.35}'::jsonb, ARRAY['Lockdown perimeter defense','Mid-range pull-ups','Strong hands for steals'], ARRAY['Pull-up mid-range jumper','Pivot fadeaway','Strip on the drive'], ARRAY['Practise defensive slides and use active hands to swipe at the ball','Build a reliable pull-up from the elbow and baseline','Be patient and strong on drives instead of rushing'], ARRAY['defense','shooting','footwork']),
('mikal-bridges', 'Mikal Bridges', 'modern', 'SF', 198, '3-and-D Wing', ARRAY['perimeter_defender','spot_up_shooter','two_way','connector'], '{"rim":0.30,"mid":0.25,"three":0.45}'::jsonb, ARRAY['Long-armed perimeter defense','Corner threes','Durability and consistency'], ARRAY['Corner catch-and-shoot three','Passing-lane deflection','Mid-range pull-up'], ARRAY['Practise corner threes, the shortest three on the floor','Contest shots with a high hand without fouling','Be in your shooting stance before the ball arrives'], ARRAY['defense','shooting']),
('jaylen-brown', 'Jaylen Brown', 'modern', 'SG', 198, 'Two-Way Wing', ARRAY['slasher','two_way','transition_threat','perimeter_defender'], '{"rim":0.45,"mid":0.20,"three":0.35}'::jsonb, ARRAY['Explosive athleticism','Strong downhill drives','Physical defense'], ARRAY['Spin move to the rim','Transition dunk','Pull-up jumper'], ARRAY['Build a spin move to punish defenders who overplay you','Sprint the floor in transition for easy baskets','Strengthen your weak hand for finishing'], ARRAY['finishing','ball_handling','defense']),
('demar-derozan', 'DeMar DeRozan', 'modern', 'SG', 198, 'Scoring Guard', ARRAY['mid_range_scorer','isolation_scorer','post_scorer'], '{"rim":0.35,"mid":0.55,"three":0.10}'::jsonb, ARRAY['Elite mid-range game','Footwork and pivots','Drawing fouls with pump fakes'], ARRAY['Pump fake into drive','Turnaround fadeaway','Spin into jumper'], ARRAY['Use pump fakes to get defenders off their feet','Practise pivot footwork: jab, spin and fadeaway','Build a reliable 15-foot jumper from both baselines'], ARRAY['footwork','shooting']),
('alex-caruso', 'Alex Caruso', 'modern', 'SG', 196, '3-and-D Wing', ARRAY['point_of_attack_defender','perimeter_defender','connector','spot_up_shooter'], '{"rim":0.35,"mid":0.15,"three":0.50}'::jsonb, ARRAY['Point-of-attack defense','High basketball IQ','Hustle plays'], ARRAY['Poking the ball from the dribbler','Diving for loose balls','Corner three'], ARRAY['Pressure the ball handler with active hands and good positioning','Chase every loose ball and long rebound','Practise catch-and-shoot corner threes'], ARRAY['defense','shooting','conditioning']),
('derrick-white', 'Derrick White', 'modern', 'SG', 193, '3-and-D Wing', ARRAY['perimeter_defender','spot_up_shooter','connector','two_way'], '{"rim":0.30,"mid":0.15,"three":0.55}'::jsonb, ARRAY['Shot-blocking as a guard','Smart team defense','Quick decisions'], ARRAY['Chase-down block','Catch-and-shoot three','Drive and kick'], ARRAY['Time chase-down blocks by trailing the shooter and jumping late','Decide to shoot, drive or pass within a second of catching','Practise catch-and-shoot threes from the wing and corner'], ARRAY['defense','shooting','passing']),
('og-anunoby', 'OG Anunoby', 'modern', 'SF', 201, '3-and-D Wing', ARRAY['perimeter_defender','spot_up_shooter','two_way'], '{"rim":0.35,"mid":0.15,"three":0.50}'::jsonb, ARRAY['Strong multi-position defense','Corner threes','Steals in passing lanes'], ARRAY['Corner three','Passing-lane steal into dunk','Straight-line drive'], ARRAY['Guard different sized players in one-on-one drills','Sit ready in the corner when teammates drive','Read the passer''s eyes to jump passing lanes'], ARRAY['defense','shooting']),
('draymond-green', 'Draymond Green', 'modern', 'PF', 198, 'Playmaking Big', ARRAY['playmaker','connector','two_way','rebounder'], '{"rim":0.50,"mid":0.15,"three":0.35}'::jsonb, ARRAY['Defensive communication','Short-roll passing','Guarding every position'], ARRAY['Short-roll pass to the corner','Grab-and-go fast break','Switching onto guards'], ARRAY['Talk constantly on defense: call out screens and switches','Practise passing out of the short roll to shooters and cutters','Grab the rebound and push the break yourself'], ARRAY['passing','defense','rebounding']),
('zion-williamson', 'Zion Williamson', 'modern', 'PF', 198, 'Athletic Finisher', ARRAY['slasher','transition_threat','post_scorer','rebounder'], '{"rim":0.80,"mid":0.15,"three":0.05}'::jsonb, ARRAY['Explosive power at the rim','Quick second jump','Strength in traffic'], ARRAY['Left-hand power drive','Offensive rebound put-back','Spin to the rim'], ARRAY['Practise quick second jumps for rebounds and put-backs','Finish strong off two feet with either hand','Build lower-body strength with squats and lunges'], ARRAY['finishing','rebounding','conditioning']),
('buddy-hield', 'Buddy Hield', 'modern', 'SG', 193, 'Sharpshooter', ARRAY['spot_up_shooter','movement_shooter','transition_threat'], '{"rim":0.15,"mid":0.10,"three":0.75}'::jsonb, ARRAY['High-volume three-point shooting','Quick release','Shooting on the move'], ARRAY['Transition pull-up three','Relocation three','Off-screen catch-and-shoot'], ARRAY['Take hundreds of threes a week and track your makes','Practise shooting right after sprinting to simulate game fatigue','Keep the same release point on every shot'], ARRAY['shooting','conditioning']),
('scottie-barnes', 'Scottie Barnes', 'modern', 'PF', 201, 'Point Forward', ARRAY['playmaker','two_way','transition_threat','connector'], '{"rim":0.55,"mid":0.20,"three":0.25}'::jsonb, ARRAY['Ball handling at forward size','Versatile defense','Transition playmaking'], ARRAY['Grab-and-go fast break','Drive and kick','Passing out of the post'], ARRAY['Practise bringing the ball up as a forward','Guard multiple positions in drills','When you drive and draw help, look for the open teammate'], ARRAY['ball_handling','passing','defense']),
('lebron-james', 'LeBron James', 'modern', 'SF', 206, 'Point Forward', ARRAY['playmaker','slasher','transition_threat','two_way'], '{"rim":0.50,"mid":0.20,"three":0.30}'::jsonb, ARRAY['Elite court vision','Power driving','Transition dominance'], ARRAY['Chase-down block','Cross-court pass off the drive','Spin into layup'], ARRAY['Keep your head up on drives to spot open teammates','Practise full-speed layups in transition','Learn to read help defense and hit the open man'], ARRAY['passing','finishing','conditioning']),
('kevin-durant', 'Kevin Durant', 'modern', 'SF', 208, 'Two-Way Wing', ARRAY['isolation_scorer','mid_range_scorer','spot_up_shooter','two_way'], '{"rim":0.25,"mid":0.40,"three":0.35}'::jsonb, ARRAY['Shooting over any defender','Guard skills at forward size','Efficient scoring'], ARRAY['Pull-up mid-range jumper','Jab-step jumper','Crossover into pull-up'], ARRAY['Practise a high release point so defenders cannot reach your shot','Work on ball handling even if you are tall','Use jab steps to create space'], ARRAY['shooting','ball_handling']),
('giannis-antetokounmpo', 'Giannis Antetokounmpo', 'modern', 'PF', 211, 'Athletic Finisher', ARRAY['slasher','transition_threat','rim_protector','rebounder','playmaker'], '{"rim":0.70,"mid":0.15,"three":0.15}'::jsonb, ARRAY['Long strides to the rim','Transition finishing','Help-side defense'], ARRAY['Euro step from the arc','Spin to the rim','Chase-down block'], ARRAY['Practise euro steps with long strides','Sprint the floor in transition every possession','Build strength to finish through contact'], ARRAY['finishing','conditioning','defense']),
('paul-george', 'Paul George', 'modern', 'SF', 203, 'Two-Way Wing', ARRAY['two_way','perimeter_defender','spot_up_shooter','isolation_scorer'], '{"rim":0.25,"mid":0.30,"three":0.45}'::jsonb, ARRAY['Smooth pull-up shooting','Long-armed defense','Steals'], ARRAY['Step-back three','Hesitation pull-up','Passing-lane steal'], ARRAY['Practise pull-up jumpers from both wings','Use your length on defense to get deflections','Keep your shooting form smooth and repeatable'], ARRAY['shooting','defense']),
('jayson-tatum', 'Jayson Tatum', 'modern', 'SF', 203, 'Two-Way Wing', ARRAY['isolation_scorer','two_way','spot_up_shooter','mid_range_scorer'], '{"rim":0.30,"mid":0.25,"three":0.45}'::jsonb, ARRAY['Three-level scoring','Step-back jumpers','Team defense and rebounding'], ARRAY['Step-back three','Jab-step pull-up','Spin fadeaway'], ARRAY['Practise step-back jumpers from the wing','Crash the defensive glass as a wing','Build your jab-step footwork'], ARRAY['shooting','footwork','rebounding']),
('anthony-davis', 'Anthony Davis', 'modern', 'PF', 208, 'Rim Protector', ARRAY['rim_protector','lob_threat','rebounder','two_way'], '{"rim":0.55,"mid":0.35,"three":0.10}'::jsonb, ARRAY['Shot blocking','Guard-like skills for a big','Lob finishing'], ARRAY['Weak-side block','Alley-oop dunk','Face-up jumper'], ARRAY['Practise timing blocks with your off hand and stay vertical','Run the floor as a big to catch lobs','Work on face-up jumpers from the elbow'], ARRAY['defense','finishing','shooting']),
('kevin-love', 'Kevin Love', 'modern', 'PF', 203, 'Stretch Big', ARRAY['stretch_big','rebounder','spot_up_shooter'], '{"rim":0.35,"mid":0.15,"three":0.50}'::jsonb, ARRAY['Rebounding position','Long outlet passing','Spot-up threes'], ARRAY['Full-court outlet pass','Pick-and-pop three','Box-out rebound'], ARRAY['Box out on every shot, then chase the ball','Practise overhead outlet passes after rebounds','Develop a catch-and-shoot three as a big'], ARRAY['rebounding','passing','shooting']),
('pascal-siakam', 'Pascal Siakam', 'modern', 'PF', 203, 'Point Forward', ARRAY['slasher','transition_threat','post_scorer','playmaker'], '{"rim":0.55,"mid":0.25,"three":0.20}'::jsonb, ARRAY['Spin moves','Running the floor','Handle for his size'], ARRAY['Spin move','Coast-to-coast drive','Post fadeaway'], ARRAY['Practise spin moves from both the perimeter and the post','Run the floor hard as a forward','Improve your handle so you can push the ball yourself'], ARRAY['footwork','finishing','ball_handling']),
('jaren-jackson-jr', 'Jaren Jackson Jr.', 'modern', 'PF', 208, 'Rim Protector', ARRAY['rim_protector','stretch_big','two_way'], '{"rim":0.35,"mid":0.15,"three":0.50}'::jsonb, ARRAY['Shot blocking','Pick-and-pop shooting','Help defense'], ARRAY['Weak-side block','Pick-and-pop three','Face-up drive'], ARRAY['Practise help-side rotations with a partner','Develop a three-point shot as a big','Stay vertical to block shots without fouling'], ARRAY['defense','shooting']),
('blake-griffin', 'Blake Griffin', 'modern', 'PF', 206, 'Athletic Finisher', ARRAY['lob_threat','playmaker','post_scorer','transition_threat'], '{"rim":0.60,"mid":0.30,"three":0.10}'::jsonb, ARRAY['Explosive dunking','Passing from the post','Strong finishing'], ARRAY['Alley-oop dunk','Post spin','Post pass to cutters'], ARRAY['Practise catching lobs and finishing high','Look for cutters when you catch in the post','Build explosive leg strength'], ARRAY['finishing','passing','post_play']),
('aaron-gordon', 'Aaron Gordon', 'modern', 'PF', 203, 'Athletic Finisher', ARRAY['lob_threat','connector','perimeter_defender','slasher'], '{"rim":0.65,"mid":0.15,"three":0.20}'::jsonb, ARRAY['Explosive leaping','Smart cutting','Versatile defense'], ARRAY['Baseline cut for alley-oop','Dunk off a cut','Short-roll finish'], ARRAY['Cut backdoor when your defender turns to watch the ball','Train explosive jumps with proper rest','Guard multiple positions in drills'], ARRAY['finishing','defense','conditioning']),
('paolo-banchero', 'Paolo Banchero', 'modern', 'PF', 208, 'Point Forward', ARRAY['isolation_scorer','playmaker','slasher','post_scorer'], '{"rim":0.45,"mid":0.30,"three":0.25}'::jsonb, ARRAY['Ball handling at forward size','Strength on drives','Passing out of double teams'], ARRAY['Power drive and finish','Spin move','Post-up pass'], ARRAY['Practise driving with your shoulder low to create contact','Work on passing out of double teams','Add a spin move to your drives'], ARRAY['ball_handling','finishing','passing']),
('bam-adebayo', 'Bam Adebayo', 'modern', 'C', 206, 'Playmaking Big', ARRAY['playmaker','two_way','perimeter_defender','connector'], '{"rim":0.55,"mid":0.40,"three":0.05}'::jsonb, ARRAY['Switching onto guards','Handoff playmaking','Elbow jumper'], ARRAY['Dribble handoff','Elbow jumper','Switching onto the ball handler'], ARRAY['Practise dribble handoffs with a guard partner','Develop a consistent elbow jumper','Slide with guards in defensive drills'], ARRAY['passing','defense','footwork']),
('domantas-sabonis', 'Domantas Sabonis', 'modern', 'C', 208, 'Playmaking Big', ARRAY['playmaker','rebounder','post_scorer','connector'], '{"rim":0.70,"mid":0.20,"three":0.10}'::jsonb, ARRAY['Relentless rebounding','Handoff playmaking','Post footwork'], ARRAY['Dribble handoff','Post spin to hook','Outlet pass'], ARRAY['Box out every shot','Practise handoffs and passes to cutters','Develop a hook shot with both hands'], ARRAY['rebounding','passing','post_play']),
('al-horford', 'Al Horford', 'modern', 'C', 206, 'Stretch Big', ARRAY['stretch_big','connector','spot_up_shooter','two_way'], '{"rim":0.30,"mid":0.20,"three":0.50}'::jsonb, ARRAY['Pick-and-pop threes','Smart team defense','High-IQ passing'], ARRAY['Pick-and-pop three','Pump fake and drive','Elbow pass to a cutter'], ARRAY['Develop a three-pointer as a big','Talk on defense and call out screens','Move the ball quickly instead of holding it'], ARRAY['shooting','passing','defense']),
('nikola-jokic', 'Nikola Jokic', 'modern', 'C', 211, 'Playmaking Big', ARRAY['playmaker','post_scorer','rebounder','floor_general'], '{"rim":0.50,"mid":0.30,"three":0.20}'::jsonb, ARRAY['Elite passing vision','Soft shooting touch','Rebounding'], ARRAY['No-look pass to a cutter','One-legged fadeaway','Handoff into dive'], ARRAY['Practise passing from the post and elbow to cutters','Work on touch shots and floaters near the rim','Grab the rebound and look to pass ahead'], ARRAY['passing','post_play','rebounding']),
('myles-turner', 'Myles Turner', 'modern', 'C', 211, 'Rim Protector', ARRAY['rim_protector','stretch_big','spot_up_shooter'], '{"rim":0.35,"mid":0.15,"three":0.50}'::jsonb, ARRAY['Shot blocking','Pick-and-pop shooting','Verticality at the rim'], ARRAY['Weak-side block','Pick-and-pop three','Vertical contest at the rim'], ARRAY['Practise block timing and keep your arms straight up','Develop a three-point shot as a big','Stay between your man and the basket'], ARRAY['defense','shooting']),
('evan-mobley', 'Evan Mobley', 'modern', 'PF', 211, 'Rim Protector', ARRAY['rim_protector','two_way','rebounder','connector'], '{"rim":0.60,"mid":0.25,"three":0.15}'::jsonb, ARRAY['Switchable defense','Shot blocking','Passing as a big'], ARRAY['Help-side block','Face-up drive','Short-roll pass'], ARRAY['Practise switching onto guards and moving your feet','Work on help-side timing for blocks','Pass out of the short roll to open teammates'], ARRAY['defense','rebounding','passing']),
('alperen-sengun', 'Alperen Sengun', 'modern', 'C', 211, 'Playmaking Big', ARRAY['post_scorer','playmaker','rebounder'], '{"rim":0.65,"mid":0.25,"three":0.10}'::jsonb, ARRAY['Post footwork','Creative passing','Soft touch'], ARRAY['Post spin','Up-and-under pump fake','Behind-the-back pass'], ARRAY['Practise post moves with pump fakes and pivots','Look for cutters from the post','Work on touch around the rim with both hands'], ARRAY['post_play','passing','footwork']),
('deandre-jordan', 'DeAndre Jordan', 'modern', 'C', 211, 'Rim Protector', ARRAY['rim_protector','lob_threat','rebounder'], '{"rim":0.95,"mid":0.05,"three":0.00}'::jsonb, ARRAY['Lob finishing','Rebounding','Shot blocking'], ARRAY['Alley-oop dunk','Weak-side block','Put-back dunk'], ARRAY['Roll hard to the rim after screens','Practise catching and finishing lobs','Box out every shot'], ARRAY['finishing','rebounding','defense']),
('joel-embiid', 'Joel Embiid', 'modern', 'C', 213, 'Post Scorer', ARRAY['post_scorer','mid_range_scorer','rim_protector','isolation_scorer'], '{"rim":0.40,"mid":0.40,"three":0.20}'::jsonb, ARRAY['Post footwork','Drawing fouls','Mid-range touch for a big'], ARRAY['Face-up jab into jumper','Post spin','Drop step'], ARRAY['Practise face-up jab steps from the elbow','Use pump fakes to draw fouls','Shoot free throws every day'], ARRAY['post_play','footwork','shooting']),
('victor-wembanyama', 'Victor Wembanyama', 'modern', 'C', 221, 'Rim Protector', ARRAY['rim_protector','stretch_big','two_way','rebounder'], '{"rim":0.40,"mid":0.20,"three":0.40}'::jsonb, ARRAY['Shot blocking','Guard skills for his size','Pull-up shooting'], ARRAY['Weak-side block','Step-back three','Spin drive'], ARRAY['Practise blocking without leaving your feet too early','Develop guard skills like dribbling and shooting even as a tall player','Work on a step-back jumper'], ARRAY['defense','shooting','ball_handling']),
('rudy-gobert', 'Rudy Gobert', 'modern', 'C', 216, 'Rim Protector', ARRAY['rim_protector','rebounder','lob_threat'], '{"rim":0.90,"mid":0.10,"three":0.00}'::jsonb, ARRAY['Rim deterrence','Rebounding','Screen setting'], ARRAY['Drop coverage contest','Screen and roll dunk','Put-back'], ARRAY['Practise drop coverage: stay between the ball and the rim','Set solid screens and roll hard','Box out every shot'], ARRAY['defense','rebounding','finishing']),
('karl-anthony-towns', 'Karl-Anthony Towns', 'modern', 'C', 213, 'Stretch Big', ARRAY['stretch_big','post_scorer','spot_up_shooter','rebounder'], '{"rim":0.40,"mid":0.15,"three":0.45}'::jsonb, ARRAY['Elite shooting for a big','Post scoring','Rebounding'], ARRAY['Pick-and-pop three','Post fadeaway','Face-up drive'], ARRAY['Develop a three-point shot as a big','Practise post moves on both blocks','Box out and rebound'], ARRAY['shooting','post_play','rebounding']),
('kristaps-porzingis', 'Kristaps Porzingis', 'modern', 'C', 218, 'Stretch Big', ARRAY['stretch_big','rim_protector','post_scorer'], '{"rim":0.35,"mid":0.25,"three":0.40}'::jsonb, ARRAY['Shooting over smaller defenders','Shot blocking','Post scoring'], ARRAY['Post fadeaway over a switch','Pick-and-pop three','Weak-side block'], ARRAY['Post up smaller defenders and shoot over them','Develop a three-pointer as a big','Practise help-side block timing'], ARRAY['shooting','post_play','defense']),
('lauri-markkanen', 'Lauri Markkanen', 'modern', 'PF', 213, 'Stretch Big', ARRAY['stretch_big','movement_shooter','spot_up_shooter'], '{"rim":0.35,"mid":0.15,"three":0.50}'::jsonb, ARRAY['Shooting off movement as a seven-footer','Attacking closeouts','Cutting'], ARRAY['Off-screen three','Closeout drive and dunk','Backdoor cut'], ARRAY['Run off screens like a guard and shoot on the catch','Attack hard when a defender closes out','Cut to the rim when your defender turns his head'], ARRAY['shooting','footwork']),
('brook-lopez', 'Brook Lopez', 'modern', 'C', 216, 'Stretch Big', ARRAY['stretch_big','rim_protector','spot_up_shooter'], '{"rim":0.35,"mid":0.10,"three":0.55}'::jsonb, ARRAY['Shot blocking','Three-point shooting','Verticality'], ARRAY['Pick-and-pop three','Vertical contest at the rim','Hook shot'], ARRAY['Develop a three-point shot as a big','Practise verticality: arms straight up on contests','Work on a short hook shot'], ARRAY['shooting','defense']),
('chet-holmgren', 'Chet Holmgren', 'modern', 'C', 216, 'Rim Protector', ARRAY['rim_protector','stretch_big','two_way'], '{"rim":0.45,"mid":0.20,"three":0.35}'::jsonb, ARRAY['Shot blocking','Shooting touch','Handle for his size'], ARRAY['Weak-side block','Pick-and-pop three','Drive and finger roll'], ARRAY['Practise help-side blocks without fouling','Develop a three-point shot','Work on your handle as a tall player'], ARRAY['defense','shooting','ball_handling']),
('marc-gasol', 'Marc Gasol', 'modern', 'C', 216, 'Playmaking Big', ARRAY['playmaker','post_scorer','rim_protector','connector'], '{"rim":0.40,"mid":0.40,"three":0.20}'::jsonb, ARRAY['High-post passing','Positional defense','Mid-range touch'], ARRAY['High-post pass to a backdoor cutter','Elbow jumper','Post hook'], ARRAY['Practise passing from the high post to cutters','Master positional defense: be in the right spot early','Develop an elbow jumper'], ARRAY['passing','defense','post_play']),
('michael-jordan', 'Michael Jordan', 'legend', 'SG', 198, 'Scoring Guard', ARRAY['isolation_scorer','mid_range_scorer','slasher','two_way'], '{"rim":0.35,"mid":0.55,"three":0.10}'::jsonb, ARRAY['Fadeaway jumper','Relentless defense','Finishing in the air'], ARRAY['Turnaround fadeaway','Hand-switch layup','Pull-up jumper'], ARRAY['Practise turnaround fadeaways from the post on both sides','Defend with full effort every possession','Work on finishing with either hand around defenders'], ARRAY['shooting','footwork','defense']),
('kobe-bryant', 'Kobe Bryant', 'legend', 'SG', 198, 'Scoring Guard', ARRAY['isolation_scorer','mid_range_scorer','post_scorer','two_way'], '{"rim":0.30,"mid":0.50,"three":0.20}'::jsonb, ARRAY['Elite footwork','Tough shot-making','Perimeter defense'], ARRAY['Turnaround fadeaway','Jab-step jumper','Baseline spin'], ARRAY['Break down footwork one move at a time: jab, pivot, fadeaway','Practise contested shots with a partner holding a pad','Train with discipline, doing extra reps after practice'], ARRAY['footwork','shooting','defense']),
('allen-iverson', 'Allen Iverson', 'legend', 'SG', 183, 'Scoring Guard', ARRAY['isolation_scorer','slasher','transition_threat'], '{"rim":0.45,"mid":0.40,"three":0.15}'::jsonb, ARRAY['Lightning crossover','Fearless drives','Speed and toughness'], ARRAY['Crossover','Floater among bigs','Pull-up jumper'], ARRAY['Practise a wide, low crossover with a hard push off your outside foot','Attack the rim without fear, using floaters over bigs','Build conditioning to play heavy minutes'], ARRAY['ball_handling','finishing','conditioning']),
('magic-johnson', 'Magic Johnson', 'legend', 'PG', 206, 'Floor General', ARRAY['floor_general','playmaker','transition_threat','post_scorer'], '{"rim":0.60,"mid":0.35,"three":0.05}'::jsonb, ARRAY['Elite fast-break passing','Size at point guard','Court vision'], ARRAY['No-look pass','Baby sky hook','Leading the fast break'], ARRAY['Push the ball ahead and keep your eyes on the floor, not the ball','Practise no-look and bounce passes with a partner','Post up smaller guards using a short hook shot'], ARRAY['passing','post_play']),
('larry-bird', 'Larry Bird', 'legend', 'SF', 206, 'Point Forward', ARRAY['playmaker','spot_up_shooter','mid_range_scorer','rebounder'], '{"rim":0.30,"mid":0.50,"three":0.20}'::jsonb, ARRAY['Shooting touch','Passing vision','Anticipation and IQ'], ARRAY['Fadeaway jumper','Touch pass to a cutter','Pump fake jumper'], ARRAY['Shoot hundreds of mid-range jumpers from spots around the arc','Pass to where your teammate is going, not where he is','Watch film to anticipate where rebounds and passes will go'], ARRAY['shooting','passing','rebounding']),
('isiah-thomas', 'Isiah Thomas', 'legend', 'PG', 185, 'Floor General', ARRAY['floor_general','slasher','playmaker','pick_and_roll_handler'], '{"rim":0.45,"mid":0.45,"three":0.10}'::jsonb, ARRAY['Quick dribble penetration','Toughness','Playmaking'], ARRAY['Crossover drive','Floater','Drive and dish'], ARRAY['Practise quick changes of direction to get into the lane','Finish with floaters over bigger defenders','Look to pass when help comes on your drive'], ARRAY['ball_handling','passing','finishing']),
('john-stockton', 'John Stockton', 'legend', 'PG', 185, 'Floor General', ARRAY['pick_and_roll_handler','floor_general','playmaker','point_of_attack_defender'], '{"rim":0.40,"mid":0.45,"three":0.15}'::jsonb, ARRAY['Pick-and-roll mastery','Steals','Efficient decision making'], ARRAY['Pick-and-roll bounce pass','Passing-lane steal','Elbow jumper'], ARRAY['Run the pick-and-roll with a partner until the reads become automatic','Anticipate passes on defense and jump the lane','Make the simple, correct pass every time'], ARRAY['passing','defense']),
('steve-nash', 'Steve Nash', 'legend', 'PG', 191, 'Floor General', ARRAY['pick_and_roll_handler','floor_general','playmaker','mid_range_scorer'], '{"rim":0.30,"mid":0.40,"three":0.30}'::jsonb, ARRAY['Elite shooting accuracy','Pick-and-roll passing','Keeping the dribble alive'], ARRAY['Probe dribble under the basket','Pick-and-roll bounce pass','Running one-legged jumper'], ARRAY['Keep your dribble alive after going under the basket and circling out','Practise pick-and-roll passes with both hands','Shoot free throws and jumpers every day for accuracy'], ARRAY['passing','shooting','ball_handling']),
('jason-kidd', 'Jason Kidd', 'legend', 'PG', 193, 'Floor General', ARRAY['floor_general','playmaker','transition_threat','rebounder','perimeter_defender'], '{"rim":0.35,"mid":0.30,"three":0.35}'::jsonb, ARRAY['Fast-break passing','Rebounding as a guard','Defense'], ARRAY['Outlet pass to start the break','Rebound and push','Lead pass in transition'], ARRAY['Rebound as a guard and push the ball immediately','Practise lead passes to teammates running the floor','Defend with active hands and good positioning'], ARRAY['passing','rebounding','defense']),
('gary-payton', 'Gary Payton', 'legend', 'PG', 193, 'Combo Guard', ARRAY['point_of_attack_defender','post_scorer','perimeter_defender','pick_and_roll_handler'], '{"rim":0.40,"mid":0.45,"three":0.15}'::jsonb, ARRAY['Elite on-ball defense','Post-ups as a guard','Active hands'], ARRAY['Full-court ball pressure','Guard post-up turnaround','Passing-lane steal'], ARRAY['Pressure the ball handler full court to wear him down','Post up smaller guards and use turnaround jumpers','Keep active hands to deflect passes'], ARRAY['defense','post_play','footwork']),
('tony-parker', 'Tony Parker', 'legend', 'PG', 188, 'Slasher', ARRAY['slasher','pick_and_roll_handler','transition_threat','mid_range_scorer'], '{"rim":0.60,"mid":0.35,"three":0.05}'::jsonb, ARRAY['Speed into the lane','Teardrop floater','Pick-and-roll control'], ARRAY['Teardrop floater','Spin in the lane','Pick-and-roll layup'], ARRAY['Practise teardrop floaters from 6 to 8 feet with a high arc','Attack the paint with speed off screens','Finish with either hand around bigs'], ARRAY['finishing','ball_handling']),
('muggsy-bogues', 'Muggsy Bogues', 'legend', 'PG', 160, 'Floor General', ARRAY['floor_general','point_of_attack_defender','playmaker','transition_threat'], '{"rim":0.45,"mid":0.45,"three":0.10}'::jsonb, ARRAY['Ball pressure','Quick hands','Fast-break passing'], ARRAY['Steal from the dribbler','Fast-break lead pass','Low-dribble penetration'], ARRAY['Stay low and use quickness to pressure the ball','Practise stealing the dribble without fouling','Push the pace and find teammates early'], ARRAY['defense','passing','ball_handling']),
('jerry-west', 'Jerry West', 'legend', 'SG', 188, 'Scoring Guard', ARRAY['mid_range_scorer','isolation_scorer','two_way'], '{"rim":0.35,"mid":0.65,"three":0.00}'::jsonb, ARRAY['Quick jump shot','Late-game scoring','Tough defense'], ARRAY['Pull-up jumper','Quick-release jumper off the dribble'], ARRAY['Practise a quick pull-up jumper off one or two dribbles','Shoot under pressure with game-winner drills','Defend with intensity every possession'], ARRAY['shooting','defense']),
('dwyane-wade', 'Dwyane Wade', 'legend', 'SG', 193, 'Slasher', ARRAY['slasher','transition_threat','two_way','mid_range_scorer'], '{"rim":0.55,"mid":0.40,"three":0.05}'::jsonb, ARRAY['Explosive drives','Shot blocking as a guard','Finishing through contact'], ARRAY['Euro step','Chase-down block','Pump fake into drive'], ARRAY['Practise euro steps at full speed','Time chase-down blocks from behind','Use pump fakes to get defenders off their feet'], ARRAY['finishing','defense','footwork']),
('ray-allen', 'Ray Allen', 'legend', 'SG', 196, 'Sharpshooter', ARRAY['movement_shooter','spot_up_shooter','mid_range_scorer'], '{"rim":0.15,"mid":0.35,"three":0.50}'::jsonb, ARRAY['Picture-perfect shooting form','Running off screens','Clutch corner threes'], ARRAY['Corner three','Coming off a pin-down','Catch-and-shoot three'], ARRAY['Shoot with the same form on every shot, from layups to threes','Run off screens in drills and catch ready to shoot','Practise corner threes after sprinting'], ARRAY['shooting','footwork','conditioning']),
('reggie-miller', 'Reggie Miller', 'legend', 'SG', 201, 'Sharpshooter', ARRAY['movement_shooter','spot_up_shooter','mid_range_scorer'], '{"rim":0.20,"mid":0.35,"three":0.45}'::jsonb, ARRAY['Constant off-ball movement','Quick release','Clutch shooting'], ARRAY['Curl three off screens','Catch-and-shoot three','Pump fake step-in jumper'], ARRAY['Never stop moving off the ball to lose your defender','Practise a quick release from different spots','Shoot under pressure in game-like drills'], ARRAY['shooting','conditioning']),
('vince-carter', 'Vince Carter', 'legend', 'SG', 198, 'Athletic Finisher', ARRAY['slasher','transition_threat','spot_up_shooter'], '{"rim":0.40,"mid":0.30,"three":0.30}'::jsonb, ARRAY['Explosive leaping','Transition dunking','Three-point range'], ARRAY['Windmill dunk','Transition dunk','Catch-and-shoot three'], ARRAY['Build explosive jumps with plyometrics and strength training','Run the floor for easy transition buckets','Develop a three-point shot to go with athleticism'], ARRAY['finishing','shooting','conditioning']),
('manu-ginobili', 'Manu Ginobili', 'legend', 'SG', 198, 'Slasher', ARRAY['slasher','playmaker','transition_threat','spot_up_shooter'], '{"rim":0.45,"mid":0.20,"three":0.35}'::jsonb, ARRAY['Euro step','Creative passing','Unpredictable drives'], ARRAY['Euro step','Wraparound pass','Left-handed drive'], ARRAY['Practise euro steps to get around defenders','Work on creative passes like wraparounds','Drive with your off hand to surprise defenders'], ARRAY['finishing','passing','ball_handling']),
('tracy-mcgrady', 'Tracy McGrady', 'legend', 'SG', 203, 'Scoring Guard', ARRAY['isolation_scorer','mid_range_scorer','playmaker','transition_threat'], '{"rim":0.35,"mid":0.40,"three":0.25}'::jsonb, ARRAY['Pull-up jumper over smaller defenders','Smooth handle for his size','Passing'], ARRAY['Pull-up jumper','Hesitation drive','Crossover into pull-up'], ARRAY['Practise pull-up jumpers off one dribble','Work on ball handling as a tall wing','Look for teammates when defenses collapse'], ARRAY['shooting','ball_handling','passing']),
('scottie-pippen', 'Scottie Pippen', 'legend', 'SF', 203, 'Point Forward', ARRAY['two_way','perimeter_defender','playmaker','transition_threat'], '{"rim":0.45,"mid":0.35,"three":0.20}'::jsonb, ARRAY['Elite perimeter defense','Point forward playmaking','Transition'], ARRAY['Passing-lane steal into fast break','Point forward fast break','Help-side block'], ARRAY['Guard multiple positions using length and footwork','Bring the ball up and run the offense as a forward','Jump passing lanes to start fast breaks'], ARRAY['defense','passing','ball_handling']),
('dominique-wilkins', 'Dominique Wilkins', 'legend', 'SF', 203, 'Athletic Finisher', ARRAY['slasher','transition_threat','isolation_scorer','rebounder'], '{"rim":0.55,"mid":0.40,"three":0.05}'::jsonb, ARRAY['Explosive dunking','Scoring in bunches','Offensive rebounding'], ARRAY['Windmill dunk','Baseline drive','Put-back dunk'], ARRAY['Build explosive leaping with plyometrics and proper rest','Attack the baseline with strong drives','Crash the offensive glass'], ARRAY['finishing','rebounding','conditioning']),
('julius-erving', 'Julius Erving', 'legend', 'SF', 201, 'Athletic Finisher', ARRAY['slasher','transition_threat','lob_threat'], '{"rim":0.65,"mid":0.35,"three":0.00}'::jsonb, ARRAY['Graceful finishing','Hang time','Fast-break scoring'], ARRAY['Baseline scoop layup','Finger roll','Free-throw-line dunk'], ARRAY['Practise finger rolls and scoop layups','Work on long strides and control in the air','Run the floor in transition'], ARRAY['finishing','conditioning']),
('charles-barkley', 'Charles Barkley', 'legend', 'PF', 198, 'Post Scorer', ARRAY['post_scorer','rebounder','transition_threat'], '{"rim":0.65,"mid":0.25,"three":0.10}'::jsonb, ARRAY['Rebounding despite height','Strength in the post','Grab-and-go fast breaks'], ARRAY['Back-down turnaround','Grab-and-go coast-to-coast','Spin baseline'], ARRAY['Box out and rebound bigger players using positioning','Use your body to back down in the post','Grab rebounds and push the ball'], ARRAY['rebounding','post_play','finishing']),
('karl-malone', 'Karl Malone', 'legend', 'PF', 206, 'Post Scorer', ARRAY['post_scorer','mid_range_scorer','rebounder','transition_threat'], '{"rim":0.50,"mid":0.50,"three":0.00}'::jsonb, ARRAY['Pick-and-pop jumper','Post strength','Durability'], ARRAY['Elbow jumper off the pick-and-roll','Post turnaround','Rim-running in transition'], ARRAY['Practise pick-and-pop jumpers from the elbow','Build strength for post play','Run the floor as a big'], ARRAY['shooting','post_play','conditioning']),
('tim-duncan', 'Tim Duncan', 'legend', 'PF', 211, 'Post Scorer', ARRAY['post_scorer','rim_protector','rebounder','mid_range_scorer'], '{"rim":0.55,"mid":0.45,"three":0.00}'::jsonb, ARRAY['Bank shot','Fundamental footwork','Team defense'], ARRAY['Bank shot off the glass','Jump hook','Face-up drive'], ARRAY['Practise bank shots from 10 to 15 feet at 45-degree angles','Master post footwork fundamentals','Protect the rim with verticality'], ARRAY['post_play','shooting','defense']),
('kevin-garnett', 'Kevin Garnett', 'legend', 'PF', 211, 'Rim Protector', ARRAY['two_way','mid_range_scorer','rim_protector','rebounder'], '{"rim":0.30,"mid":0.68,"three":0.02}'::jsonb, ARRAY['Defensive intensity','Mid-range jumper','Communication'], ARRAY['Turnaround jumper','Help-side block','Elbow jumper'], ARRAY['Talk constantly on defense','Develop a mid-range jumper as a big','Play with energy every possession'], ARRAY['defense','shooting','rebounding']),
('dirk-nowitzki', 'Dirk Nowitzki', 'legend', 'PF', 213, 'Stretch Big', ARRAY['stretch_big','mid_range_scorer','post_scorer','isolation_scorer'], '{"rim":0.20,"mid":0.55,"three":0.25}'::jsonb, ARRAY['One-legged fadeaway','Shooting touch as a seven-footer','Pick-and-pop'], ARRAY['One-legged fadeaway','Pick-and-pop jumper','Pump fake drive'], ARRAY['Practise the one-legged fadeaway from the post','Develop a jumper as a big','Use pump fakes to get defenders in the air'], ARRAY['shooting','footwork','post_play']),
('shaquille-oneal', 'Shaquille O''Neal', 'legend', 'C', 216, 'Post Scorer', ARRAY['post_scorer','rebounder','rim_protector'], '{"rim":0.90,"mid":0.10,"three":0.00}'::jsonb, ARRAY['Overpowering post play','Finishing strength','Rebounding'], ARRAY['Drop step dunk','Baby hook','Spin in the post'], ARRAY['Establish deep post position with your body','Practise drop steps to both sides','Finish strong with two hands'], ARRAY['post_play','finishing','rebounding']),
('hakeem-olajuwon', 'Hakeem Olajuwon', 'legend', 'C', 213, 'Post Scorer', ARRAY['post_scorer','rim_protector','two_way','rebounder'], '{"rim":0.55,"mid":0.45,"three":0.00}'::jsonb, ARRAY['Elite post footwork','Shot blocking','Quick feet for a big'], ARRAY['Dream Shake','Up-and-under','Turnaround jumper'], ARRAY['Practise post fakes and pivots to create space','Use quick feet to beat bigger defenders','Time blocks without fouling'], ARRAY['footwork','post_play','defense']),
('kareem-abdul-jabbar', 'Kareem Abdul-Jabbar', 'legend', 'C', 218, 'Post Scorer', ARRAY['post_scorer','rim_protector','rebounder'], '{"rim":0.70,"mid":0.30,"three":0.00}'::jsonb, ARRAY['Unblockable skyhook','Longevity','Rebounding'], ARRAY['Skyhook','Turnaround jumper'], ARRAY['Practise the hook shot with both hands','Work on a high release point','Box out and rebound'], ARRAY['post_play','shooting','rebounding']),
('bill-russell', 'Bill Russell', 'legend', 'C', 208, 'Rim Protector', ARRAY['rim_protector','rebounder','transition_threat','two_way'], '{"rim":0.80,"mid":0.20,"three":0.00}'::jsonb, ARRAY['Shot blocking','Rebounding','Winning team defense'], ARRAY['Block kept in play to a teammate','Outlet pass to start the break'], ARRAY['Block shots toward a teammate instead of out of bounds','Rebound and outlet quickly','Focus on team defense and communication'], ARRAY['defense','rebounding','passing']),
('david-robinson', 'David Robinson', 'legend', 'C', 216, 'Rim Protector', ARRAY['rim_protector','rebounder','transition_threat','mid_range_scorer'], '{"rim":0.60,"mid":0.40,"three":0.00}'::jsonb, ARRAY['Shot blocking','Running the floor','Face-up jumper'], ARRAY['Weak-side block','Face-up jumper','Transition dunk'], ARRAY['Run the floor as a big for easy baskets','Practise blocking shots with good timing','Develop a face-up jumper'], ARRAY['defense','conditioning','shooting']),
('dikembe-mutombo', 'Dikembe Mutombo', 'legend', 'C', 218, 'Rim Protector', ARRAY['rim_protector','rebounder','post_scorer'], '{"rim":0.85,"mid":0.15,"three":0.00}'::jsonb, ARRAY['Elite shot blocking','Rebounding','Paint deterrence'], ARRAY['Weak-side block','Hook shot'], ARRAY['Practise block timing and staying vertical','Box out every shot','Hold your ground in the paint'], ARRAY['defense','rebounding']),
('patrick-ewing', 'Patrick Ewing', 'legend', 'C', 213, 'Post Scorer', ARRAY['post_scorer','mid_range_scorer','rim_protector','rebounder'], '{"rim":0.50,"mid":0.50,"three":0.00}'::jsonb, ARRAY['Post scoring','Baseline jumper','Shot blocking'], ARRAY['Baseline turnaround jumper','Post spin','Weak-side block'], ARRAY['Practise turnaround jumpers from the baseline','Develop post footwork on both blocks','Time blocks with your off hand'], ARRAY['post_play','shooting','defense']),
('yao-ming', 'Yao Ming', 'legend', 'C', 229, 'Post Scorer', ARRAY['post_scorer','mid_range_scorer','rim_protector'], '{"rim":0.55,"mid":0.45,"three":0.00}'::jsonb, ARRAY['Soft shooting touch','Post scoring','Free-throw shooting for a big'], ARRAY['Turnaround jumper','Post hook','High-post jumper'], ARRAY['Develop soft touch around the rim','Practise free throws daily','Work on post footwork'], ARRAY['post_play','shooting','footwork']),
('pau-gasol', 'Pau Gasol', 'legend', 'PF', 213, 'Playmaking Big', ARRAY['post_scorer','playmaker','rebounder','mid_range_scorer'], '{"rim":0.55,"mid":0.43,"three":0.02}'::jsonb, ARRAY['Skilled post footwork','Passing from the post','Soft touch'], ARRAY['Post up-and-under','High-low pass','Hook shot'], ARRAY['Practise post moves with both hands','Pass from the post to cutters','Develop soft touch'], ARRAY['post_play','passing','footwork']),
('wilt-chamberlain', 'Wilt Chamberlain', 'legend', 'C', 216, 'Post Scorer', ARRAY['post_scorer','rebounder','rim_protector'], '{"rim":0.80,"mid":0.20,"three":0.00}'::jsonb, ARRAY['Dominant post scoring','Rebounding','Athleticism and stamina'], ARRAY['Finger roll','Fadeaway bank shot'], ARRAY['Establish post position and finish with a finger roll','Rebound aggressively','Build conditioning to play hard all game'], ARRAY['post_play','rebounding','conditioning'])
ON CONFLICT (slug) DO NOTHING;
