-- 00014_training_programs.sql
-- Multi-week training programs (day-by-day plans made of drills, gym exercises,
-- study lessons and tests), plus each player's enrollment and completed days.
-- Program content is added at the end. Safe to re-run.

CREATE TABLE IF NOT EXISTS public.training_programs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  slug text UNIQUE NOT NULL,
  name text NOT NULL,
  description text NOT NULL,
  goal text NOT NULL CHECK (goal IN ('shooting', 'ball_handling', 'finishing', 'athleticism', 'vertical', 'complete', 'in_season')),
  level text NOT NULL CHECK (level IN ('beginner', 'intermediate', 'advanced', 'all')),
  position text NOT NULL DEFAULT 'any' CHECK (position IN ('any', 'guard', 'wing', 'big')),
  weeks smallint NOT NULL CHECK (weeks BETWEEN 1 AND 16),
  sessions_per_week smallint NOT NULL CHECK (sessions_per_week BETWEEN 1 AND 7),
  season text NOT NULL DEFAULT 'any' CHECK (season IN ('off_season', 'in_season', 'any')),
  display_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.program_days (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  program_id uuid NOT NULL REFERENCES public.training_programs(id) ON DELETE CASCADE,
  week smallint NOT NULL CHECK (week >= 1),
  day smallint NOT NULL CHECK (day >= 1),
  title text NOT NULL,
  focus text NOT NULL,
  estimated_minutes integer NOT NULL CHECK (estimated_minutes BETWEEN 5 AND 180),
  items jsonb NOT NULL DEFAULT '[]',
  UNIQUE (program_id, week, day)
);
CREATE INDEX IF NOT EXISTS idx_program_days_program ON public.program_days(program_id, week, day);

-- A player follows one program at a time (older enrollments are kept as history)
CREATE TABLE IF NOT EXISTS public.program_enrollments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  program_id uuid NOT NULL REFERENCES public.training_programs(id) ON DELETE CASCADE,
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'completed', 'stopped')),
  started_at timestamptz NOT NULL DEFAULT now(),
  finished_at timestamptz
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_program_enrollments_one_active
  ON public.program_enrollments(user_id) WHERE status = 'active';

CREATE TABLE IF NOT EXISTS public.program_day_completions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  enrollment_id uuid NOT NULL REFERENCES public.program_enrollments(id) ON DELETE CASCADE,
  program_day_id uuid NOT NULL REFERENCES public.program_days(id) ON DELETE CASCADE,
  completed_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (enrollment_id, program_day_id)
);

ALTER TABLE public.training_programs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.program_days ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.program_enrollments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.program_day_completions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Players can view programs" ON public.training_programs;
CREATE POLICY "Players can view programs" ON public.training_programs FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "Players can view program days" ON public.program_days;
CREATE POLICY "Players can view program days" ON public.program_days FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "Users manage own enrollments" ON public.program_enrollments;
CREATE POLICY "Users manage own enrollments" ON public.program_enrollments
  FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users manage own day completions" ON public.program_day_completions;
CREATE POLICY "Users manage own day completions" ON public.program_day_completions
  FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- This project does not auto-grant new tables to the API roles (see 00008)
GRANT SELECT ON public.training_programs, public.program_days TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.program_enrollments, public.program_day_completions TO authenticated;
GRANT ALL ON public.training_programs, public.program_days, public.program_enrollments, public.program_day_completions TO service_role;
REVOKE ALL ON public.training_programs, public.program_days, public.program_enrollments, public.program_day_completions FROM anon;

-- =============================================================================
-- PROGRAMS
-- =============================================================================
-- HoopIQ training programs (generated). Safe to re-run.

INSERT INTO public.training_programs (slug, name, description, goal, level, position, weeks, sessions_per_week, season, display_order) VALUES
  ('shooting-foundations', 'Shooting Foundations', 'Build a repeatable jump shot from the ground up. Four weeks of form work, footwork into the shot, and gradually adding range, finishing with a shooting check-in to measure progress.', 'shooting', 'beginner', 'any', 4, 3, 'any', 1),
  ('ten-k-shot-summer', '10,000 Shot Summer', 'A six-week, high-volume off-season shooting plan that adds up to 10,000 shots. Each week mixes catch-and-shoot, off-the-dribble, movement, game-speed and competition days, with shot goals that climb as the summer goes on.', 'shooting', 'intermediate', 'any', 6, 5, 'off_season', 2),
  ('handle-builder', 'Handle Builder', 'Four weeks to a tighter, quicker handle. Progresses from stationary control and weak-hand work to two-ball drills, change-of-pace moves and combo chains that finish at the rim or with a pull-up.', 'ball_handling', 'all', 'guard', 4, 4, 'any', 3),
  ('finish-at-the-rim', 'Finish at the Rim', 'Score more around the basket with both hands. Four weeks of footwork, angles, touch finishes and body control that build toward game-speed finishing.', 'finishing', 'intermediate', 'any', 4, 3, 'any', 4),
  ('vertical-jump-8-week', '8-Week Vertical Jump Program', 'An eight-week off-season plan to jump higher. Progressive plyometrics and strength work with a deload in week 4 and a taper in week 8. You test standing, approach and broad jumps in week 1 and again at the end.', 'vertical', 'intermediate', 'any', 8, 3, 'off_season', 5),
  ('guard-offseason', 'Guard Off-Season Complete', 'A complete six-week off-season plan for guards: ball handling, pull-up shooting, finishing, game-speed conditioning, strength and plyometrics, plus weekly film and IQ study. Includes a 5-10-5 agility test at the start and end.', 'complete', 'intermediate', 'guard', 6, 4, 'off_season', 6),
  ('wing-offseason', 'Wing Off-Season Complete', 'A complete six-week off-season plan for wings: catch-and-shoot and relocation shooting, attacking closeouts, finishing, on-ball and help defense, plus strength, plyometrics and weekly IQ study. Includes a lane agility test at the start and end.', 'complete', 'intermediate', 'wing', 6, 4, 'off_season', 7),
  ('big-development', 'Big Man Development', 'A six-week off-season plan for post players: post moves and counters, rebounding, touch around the rim, face-up game and free throws, rim-protection footwork, plus strength, power and weekly study. Includes a standing vertical test at the start and end.', 'complete', 'intermediate', 'big', 6, 4, 'off_season', 8),
  ('in-season-maintenance', 'In-Season Maintenance', 'Two short sessions a week to keep your shot, handle and strength sharp during the season without wearing out your legs. Light lifting, quality shooting and a weekly study topic.', 'in_season', 'all', 'any', 4, 2, 'in_season', 9),
  ('beginner-complete', 'Complete Beginner Player', 'The best place to start. Four weeks covering dribbling, shooting form, layups, footwork, defense and basic strength, with one short study lesson each week to build your basketball IQ.', 'complete', 'beginner', 'any', 4, 3, 'any', 10)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.program_days (program_id, week, day, title, focus, estimated_minutes, items)
SELECT p.id, v.week, v.day, v.title, v.focus, v.estimated_minutes, v.items::jsonb
FROM (VALUES
  ('shooting-foundations', 1, 1, 'Form First', 'Week 1: one-hand form, straight elbow, high follow-through', 35, '[{"type":"note","text":"Start 3 feet from the rim. Only step back after 7 of 10 makes."},{"type":"drill","slug":"lie-down-form-shots"},{"type":"drill","slug":"form-shooting-one-hand"},{"type":"drill","slug":"form-shooting-ladder"},{"type":"study","topic_slug":"shooting-mechanics"}]'),
  ('shooting-foundations', 1, 2, 'Close-Range Touch', 'Week 1: soft touch and using the backboard', 35, '[{"type":"drill","slug":"mikan-drill"},{"type":"drill","slug":"bank-shot-series"},{"type":"drill","slug":"form-shooting-one-hand","note":"Focus on holding your follow-through"},{"type":"drill","slug":"free-throw-routine-builder"}]'),
  ('shooting-foundations', 1, 3, 'Balance and Base', 'Week 1: balanced stance and shot pocket', 50, '[{"type":"drill","slug":"triple-threat-stance"},{"type":"drill","slug":"form-shooting-ladder"},{"type":"drill","slug":"bank-shot-series"},{"type":"drill","slug":"around-the-world","note":"Stay inside the lane this week"},{"type":"drill","slug":"free-throw-routine-builder"}]'),
  ('shooting-foundations', 2, 1, 'Footwork Into the Shot', 'Week 2: hop vs 1-2 step on the catch', 40, '[{"type":"drill","slug":"one-two-step-vs-hop"},{"type":"drill","slug":"form-shooting-one-hand","note":"Warm up with 20 makes"},{"type":"drill","slug":"hop-vs-one-two-shooting"},{"type":"drill","slug":"free-throw-routine-builder"}]'),
  ('shooting-foundations', 2, 2, 'Catch and Shoot Rhythm', 'Week 2: ready hands and quick feet', 35, '[{"type":"drill","slug":"form-shooting-ladder"},{"type":"drill","slug":"spin-out-catch-and-shoot"},{"type":"drill","slug":"elbow-to-elbow-shooting"},{"type":"drill","slug":"mikan-drill"}]'),
  ('shooting-foundations', 2, 3, 'Midrange Intro', 'Week 2: same form from a little farther out', 45, '[{"type":"drill","slug":"lie-down-form-shots"},{"type":"drill","slug":"spin-out-catch-and-shoot"},{"type":"drill","slug":"five-spot-midrange","note":"Start at the short spots"},{"type":"drill","slug":"around-the-world"},{"type":"drill","slug":"free-throw-routine-builder"}]'),
  ('shooting-foundations', 3, 1, 'Range and Rhythm', 'Week 3: midrange volume with good form', 45, '[{"type":"drill","slug":"form-shooting-one-hand"},{"type":"drill","slug":"five-spot-midrange"},{"type":"drill","slug":"hop-vs-one-two-shooting"},{"type":"drill","slug":"free-throw-routine-builder"},{"type":"note","text":"If form breaks down, move closer. Makes build confidence."}]'),
  ('shooting-foundations', 3, 2, 'Shooting on the Move', 'Week 3: moving to the ball and squaring up', 40, '[{"type":"drill","slug":"form-shooting-ladder"},{"type":"drill","slug":"elbow-to-elbow-shooting"},{"type":"drill","slug":"spin-out-catch-and-shoot"},{"type":"drill","slug":"bank-shot-series"}]'),
  ('shooting-foundations', 3, 3, 'Around the Arc Warm-Up', 'Week 3: consistency at every spot', 45, '[{"type":"drill","slug":"form-shooting-one-hand"},{"type":"drill","slug":"around-the-world"},{"type":"drill","slug":"five-spot-midrange"},{"type":"drill","slug":"free-throw-routine-builder","note":"Track your makes out of 20"}]'),
  ('shooting-foundations', 4, 1, 'Put It Together', 'Week 4: full shooting routine at game rhythm', 50, '[{"type":"drill","slug":"form-shooting-ladder"},{"type":"drill","slug":"spin-out-catch-and-shoot"},{"type":"drill","slug":"five-spot-midrange"},{"type":"drill","slug":"elbow-to-elbow-shooting"},{"type":"drill","slug":"free-throw-routine-builder"}]'),
  ('shooting-foundations', 4, 2, 'Touch and Footwork Review', 'Week 4: sharpen footwork and close-range touch', 50, '[{"type":"drill","slug":"mikan-drill"},{"type":"drill","slug":"hop-vs-one-two-shooting"},{"type":"drill","slug":"around-the-world"},{"type":"drill","slug":"bank-shot-series"},{"type":"study","topic_slug":"shooting-mechanics"}]'),
  ('shooting-foundations', 4, 3, 'Shooting Check-In', 'Week 4: measure your progress', 45, '[{"type":"note","text":"Record your makes out of 50 from the five midrange spots and compare with week 1."},{"type":"drill","slug":"form-shooting-one-hand"},{"type":"drill","slug":"five-spot-midrange"},{"type":"drill","slug":"around-the-world"},{"type":"drill","slug":"free-throw-routine-builder"},{"type":"note","text":"Ready for more? Move on to the 10,000 Shot Summer."}]'),
  ('ten-k-shot-summer', 1, 1, 'Catch-and-Shoot Volume', 'Week 1 (Build the base): feet set, quick release', 62, '[{"type":"note","text":"Shot goal: 280 attempts today (running total 280). Log your makes."},{"type":"drill","slug":"form-shooting-one-hand","note":"Warm up: 25 makes"},{"type":"drill","slug":"spin-out-catch-and-shoot"},{"type":"drill","slug":"five-spot-midrange"},{"type":"drill","slug":"free-throw-routine-builder"},{"type":"study","topic_slug":"shooting-mechanics"}]'),
  ('ten-k-shot-summer', 1, 2, 'Off-the-Dribble Shooting', 'Week 1 (Build the base): pull-ups with a strong, balanced gather', 62, '[{"type":"note","text":"Shot goal: 280 attempts today (running total 560). Log your makes."},{"type":"drill","slug":"form-shooting-ladder"},{"type":"drill","slug":"one-dribble-pull-up"},{"type":"drill","slug":"shot-fake-one-dribble"},{"type":"drill","slug":"ten-in-a-row-free-throws"}]'),
  ('ten-k-shot-summer', 1, 3, 'Midrange and Movement', 'Week 1 (Build the base): shooting on the move and relocating', 62, '[{"type":"note","text":"Shot goal: 280 attempts today (running total 840). Log your makes."},{"type":"drill","slug":"mikan-drill","note":"Touch warm-up"},{"type":"drill","slug":"elbow-to-elbow-shooting"},{"type":"drill","slug":"five-spot-midrange"},{"type":"drill","slug":"around-the-world"}]'),
  ('ten-k-shot-summer', 1, 4, 'Game-Speed Shooting', 'Week 1 (Build the base): shots at game pace and free throws on tired legs', 62, '[{"type":"note","text":"Shot goal: 280 attempts today (running total 1,120). Log your makes."},{"type":"drill","slug":"form-shooting-one-hand"},{"type":"drill","slug":"transition-pull-ups"},{"type":"drill","slug":"corner-three-series"},{"type":"drill","slug":"tired-legs-free-throws"}]'),
  ('ten-k-shot-summer', 1, 5, 'Competition Day', 'Week 1 (Build the base): score yourself and beat last week', 62, '[{"type":"note","text":"Shot goal: 280 attempts today (running total 1,400). Log your makes."},{"type":"drill","slug":"form-shooting-ladder"},{"type":"drill","slug":"around-the-world"},{"type":"drill","slug":"hundred-makes-challenge"},{"type":"drill","slug":"ten-in-a-row-free-throws"}]'),
  ('ten-k-shot-summer', 2, 1, 'Catch-and-Shoot Volume', 'Week 2 (Add range): feet set, quick release', 68, '[{"type":"note","text":"Shot goal: 310 attempts today (running total 1,710). Log your makes."},{"type":"drill","slug":"form-shooting-one-hand","note":"Warm up: 25 makes"},{"type":"drill","slug":"five-spot-threes"},{"type":"drill","slug":"hop-vs-one-two-shooting"},{"type":"drill","slug":"ten-in-a-row-free-throws"}]'),
  ('ten-k-shot-summer', 2, 2, 'Off-the-Dribble Shooting', 'Week 2 (Add range): pull-ups with a strong, balanced gather', 68, '[{"type":"note","text":"Shot goal: 310 attempts today (running total 2,020). Log your makes."},{"type":"drill","slug":"form-shooting-ladder"},{"type":"drill","slug":"one-dribble-pull-up"},{"type":"drill","slug":"two-dribble-pull-up"},{"type":"drill","slug":"ten-in-a-row-free-throws"}]'),
  ('ten-k-shot-summer', 2, 3, 'Midrange and Movement', 'Week 2 (Add range): shooting on the move and relocating', 68, '[{"type":"note","text":"Shot goal: 310 attempts today (running total 2,330). Log your makes."},{"type":"drill","slug":"mikan-drill","note":"Touch warm-up"},{"type":"drill","slug":"elbow-to-elbow-shooting"},{"type":"drill","slug":"five-spot-midrange"},{"type":"drill","slug":"drift-and-relocate"}]'),
  ('ten-k-shot-summer', 2, 4, 'Game-Speed Shooting', 'Week 2 (Add range): shots at game pace and free throws on tired legs', 68, '[{"type":"note","text":"Shot goal: 310 attempts today (running total 2,640). Log your makes."},{"type":"drill","slug":"form-shooting-one-hand"},{"type":"drill","slug":"transition-pull-ups"},{"type":"drill","slug":"five-spot-threes"},{"type":"drill","slug":"tired-legs-free-throws"}]'),
  ('ten-k-shot-summer', 2, 5, 'Competition Day', 'Week 2 (Add range): score yourself and beat last week', 68, '[{"type":"note","text":"Shot goal: 310 attempts today (running total 2,950). Log your makes."},{"type":"drill","slug":"form-shooting-ladder"},{"type":"drill","slug":"beat-the-pro"},{"type":"drill","slug":"hundred-makes-challenge"},{"type":"drill","slug":"ten-in-a-row-free-throws"}]'),
  ('ten-k-shot-summer', 3, 1, 'Catch-and-Shoot Volume', 'Week 3 (Add the dribble): feet set, quick release', 73, '[{"type":"note","text":"Shot goal: 330 attempts today (running total 3,280). Log your makes."},{"type":"drill","slug":"form-shooting-one-hand","note":"Warm up: 25 makes"},{"type":"drill","slug":"corner-three-series"},{"type":"drill","slug":"spin-out-catch-and-shoot"},{"type":"drill","slug":"ten-in-a-row-free-throws"}]'),
  ('ten-k-shot-summer', 3, 2, 'Off-the-Dribble Shooting', 'Week 3 (Add the dribble): pull-ups with a strong, balanced gather', 73, '[{"type":"note","text":"Shot goal: 330 attempts today (running total 3,610). Log your makes."},{"type":"drill","slug":"form-shooting-ladder"},{"type":"drill","slug":"two-dribble-pull-up"},{"type":"drill","slug":"shot-fake-one-dribble"},{"type":"drill","slug":"ten-in-a-row-free-throws"}]'),
  ('ten-k-shot-summer', 3, 3, 'Midrange and Movement', 'Week 3 (Add the dribble): shooting on the move and relocating', 73, '[{"type":"note","text":"Shot goal: 330 attempts today (running total 3,940). Log your makes."},{"type":"drill","slug":"mikan-drill","note":"Touch warm-up"},{"type":"drill","slug":"elbow-to-elbow-shooting"},{"type":"drill","slug":"five-spot-midrange"},{"type":"drill","slug":"around-the-world"}]'),
  ('ten-k-shot-summer', 3, 4, 'Game-Speed Shooting', 'Week 3 (Add the dribble): shots at game pace and free throws on tired legs', 73, '[{"type":"note","text":"Shot goal: 330 attempts today (running total 4,270). Log your makes."},{"type":"drill","slug":"form-shooting-one-hand"},{"type":"drill","slug":"transition-pull-ups"},{"type":"drill","slug":"corner-three-series"},{"type":"drill","slug":"tired-legs-free-throws"}]'),
  ('ten-k-shot-summer', 3, 5, 'Competition Day', 'Week 3 (Add the dribble): score yourself and beat last week', 73, '[{"type":"note","text":"Shot goal: 330 attempts today (running total 4,600). Log your makes."},{"type":"drill","slug":"form-shooting-ladder"},{"type":"drill","slug":"thirty-one"},{"type":"drill","slug":"hundred-makes-challenge"},{"type":"drill","slug":"ten-in-a-row-free-throws"},{"type":"study","topic_slug":"film-study"}]'),
  ('ten-k-shot-summer', 4, 1, 'Catch-and-Shoot Volume', 'Week 4 (Game speed): feet set, quick release', 77, '[{"type":"note","text":"Shot goal: 350 attempts today (running total 4,950). Log your makes."},{"type":"drill","slug":"form-shooting-one-hand","note":"Warm up: 25 makes"},{"type":"drill","slug":"five-spot-threes"},{"type":"drill","slug":"drift-and-relocate"},{"type":"drill","slug":"ten-in-a-row-free-throws"}]'),
  ('ten-k-shot-summer', 4, 2, 'Off-the-Dribble Shooting', 'Week 4 (Game speed): pull-ups with a strong, balanced gather', 77, '[{"type":"note","text":"Shot goal: 350 attempts today (running total 5,300). Log your makes."},{"type":"drill","slug":"form-shooting-ladder"},{"type":"drill","slug":"two-dribble-pull-up"},{"type":"drill","slug":"one-dribble-pull-up"},{"type":"drill","slug":"ten-in-a-row-free-throws"}]'),
  ('ten-k-shot-summer', 4, 3, 'Midrange and Movement', 'Week 4 (Game speed): shooting on the move and relocating', 77, '[{"type":"note","text":"Shot goal: 350 attempts today (running total 5,650). Log your makes."},{"type":"drill","slug":"mikan-drill","note":"Touch warm-up"},{"type":"drill","slug":"elbow-to-elbow-shooting"},{"type":"drill","slug":"five-spot-midrange"},{"type":"drill","slug":"drift-and-relocate"}]'),
  ('ten-k-shot-summer', 4, 4, 'Game-Speed Shooting', 'Week 4 (Game speed): shots at game pace and free throws on tired legs', 77, '[{"type":"note","text":"Shot goal: 350 attempts today (running total 6,000). Log your makes."},{"type":"drill","slug":"form-shooting-one-hand"},{"type":"drill","slug":"transition-pull-ups"},{"type":"drill","slug":"sprint-back-threes"},{"type":"drill","slug":"tired-legs-free-throws"}]'),
  ('ten-k-shot-summer', 4, 5, 'Competition Day', 'Week 4 (Game speed): score yourself and beat last week', 77, '[{"type":"note","text":"Shot goal: 350 attempts today (running total 6,350). Log your makes."},{"type":"drill","slug":"form-shooting-ladder"},{"type":"drill","slug":"beat-the-pro"},{"type":"drill","slug":"hundred-makes-challenge"},{"type":"drill","slug":"free-throw-pressure-ladder"},{"type":"study","topic_slug":"mental-game"}]'),
  ('ten-k-shot-summer', 5, 1, 'Catch-and-Shoot Volume', 'Week 5 (Advanced counters): feet set, quick release', 81, '[{"type":"note","text":"Shot goal: 370 attempts today (running total 6,720). Log your makes."},{"type":"drill","slug":"form-shooting-one-hand","note":"Warm up: 25 makes"},{"type":"drill","slug":"drift-and-relocate"},{"type":"drill","slug":"corner-three-series"},{"type":"drill","slug":"ten-in-a-row-free-throws"}]'),
  ('ten-k-shot-summer', 5, 2, 'Off-the-Dribble Shooting', 'Week 5 (Advanced counters): pull-ups with a strong, balanced gather', 81, '[{"type":"note","text":"Shot goal: 370 attempts today (running total 7,090). Log your makes."},{"type":"drill","slug":"form-shooting-ladder"},{"type":"drill","slug":"step-back-jumper"},{"type":"drill","slug":"side-step-three"},{"type":"drill","slug":"ten-in-a-row-free-throws"}]'),
  ('ten-k-shot-summer', 5, 3, 'Midrange and Movement', 'Week 5 (Advanced counters): shooting on the move and relocating', 81, '[{"type":"note","text":"Shot goal: 370 attempts today (running total 7,460). Log your makes."},{"type":"drill","slug":"mikan-drill","note":"Touch warm-up"},{"type":"drill","slug":"elbow-to-elbow-shooting"},{"type":"drill","slug":"five-spot-midrange"},{"type":"drill","slug":"shot-fake-one-dribble"}]'),
  ('ten-k-shot-summer', 5, 4, 'Game-Speed Shooting', 'Week 5 (Advanced counters): shots at game pace and free throws on tired legs', 81, '[{"type":"note","text":"Shot goal: 370 attempts today (running total 7,830). Log your makes."},{"type":"drill","slug":"form-shooting-one-hand"},{"type":"drill","slug":"sprint-and-shoot-intervals"},{"type":"drill","slug":"sprint-back-threes"},{"type":"drill","slug":"tired-legs-free-throws"}]'),
  ('ten-k-shot-summer', 5, 5, 'Competition Day', 'Week 5 (Advanced counters): score yourself and beat last week', 81, '[{"type":"note","text":"Shot goal: 370 attempts today (running total 8,200). Log your makes."},{"type":"drill","slug":"form-shooting-ladder"},{"type":"drill","slug":"thirty-one"},{"type":"drill","slug":"hundred-makes-challenge"},{"type":"drill","slug":"free-throw-pressure-ladder"}]'),
  ('ten-k-shot-summer', 6, 1, 'Catch-and-Shoot Volume', 'Week 6 (Finish strong): feet set, quick release', 79, '[{"type":"note","text":"Shot goal: 360 attempts today (running total 8,560). Log your makes."},{"type":"drill","slug":"form-shooting-one-hand","note":"Warm up: 25 makes"},{"type":"drill","slug":"five-spot-threes"},{"type":"drill","slug":"sprint-back-threes"},{"type":"drill","slug":"ten-in-a-row-free-throws"}]'),
  ('ten-k-shot-summer', 6, 2, 'Off-the-Dribble Shooting', 'Week 6 (Finish strong): pull-ups with a strong, balanced gather', 79, '[{"type":"note","text":"Shot goal: 360 attempts today (running total 8,920). Log your makes."},{"type":"drill","slug":"form-shooting-ladder"},{"type":"drill","slug":"step-back-jumper"},{"type":"drill","slug":"two-dribble-pull-up"},{"type":"drill","slug":"ten-in-a-row-free-throws"}]'),
  ('ten-k-shot-summer', 6, 3, 'Midrange and Movement', 'Week 6 (Finish strong): shooting on the move and relocating', 79, '[{"type":"note","text":"Shot goal: 360 attempts today (running total 9,280). Log your makes."},{"type":"drill","slug":"mikan-drill","note":"Touch warm-up"},{"type":"drill","slug":"elbow-to-elbow-shooting"},{"type":"drill","slug":"five-spot-midrange"},{"type":"drill","slug":"drift-and-relocate"}]'),
  ('ten-k-shot-summer', 6, 4, 'Game-Speed Shooting', 'Week 6 (Finish strong): shots at game pace and free throws on tired legs', 79, '[{"type":"note","text":"Shot goal: 360 attempts today (running total 9,640). Log your makes."},{"type":"drill","slug":"form-shooting-one-hand"},{"type":"drill","slug":"sprint-and-shoot-intervals"},{"type":"drill","slug":"corner-three-series"},{"type":"drill","slug":"tired-legs-free-throws"}]'),
  ('ten-k-shot-summer', 6, 5, 'Competition Day', 'Week 6 (Finish strong): score yourself and beat last week', 79, '[{"type":"note","text":"Shot goal: 360 attempts today (running total 10,000). Log your makes. That completes 10,000 shots!"},{"type":"drill","slug":"form-shooting-ladder"},{"type":"drill","slug":"game-winner-countdown"},{"type":"drill","slug":"hundred-makes-challenge"},{"type":"drill","slug":"free-throw-pressure-ladder"}]'),
  ('handle-builder', 1, 1, 'Stationary Control', 'Week 1: pound hard, eyes up', 30, '[{"type":"drill","slug":"pound-dribble-series"},{"type":"drill","slug":"ball-wraps"},{"type":"drill","slug":"figure-eight-dribble"},{"type":"drill","slug":"v-dribble"},{"type":"drill","slug":"stationary-crossover"}]'),
  ('handle-builder', 1, 2, 'Weak-Hand Day', 'Week 1: build trust in your off hand', 30, '[{"type":"drill","slug":"weak-hand-stationary"},{"type":"drill","slug":"between-legs-stationary"},{"type":"drill","slug":"full-court-speed-dribble","note":"Weak hand only on the way back"},{"type":"drill","slug":"weak-hand-layups"}]'),
  ('handle-builder', 1, 3, 'Two-Ball Intro', 'Week 1: rhythm with two balls', 25, '[{"type":"drill","slug":"ball-wraps"},{"type":"drill","slug":"two-ball-pound"},{"type":"drill","slug":"pound-dribble-series"},{"type":"drill","slug":"full-court-speed-dribble"}]'),
  ('handle-builder', 1, 4, 'Handle to Finish', 'Week 1: attack the rim under control', 40, '[{"type":"drill","slug":"stationary-crossover"},{"type":"drill","slug":"full-court-dribble-sprints"},{"type":"drill","slug":"power-layup-series"},{"type":"drill","slug":"weak-hand-layups"},{"type":"study","topic_slug":"ball-handling"}]'),
  ('handle-builder', 2, 1, 'Quick Hands', 'Week 2: faster, lower dribbles', 30, '[{"type":"drill","slug":"pound-dribble-series"},{"type":"drill","slug":"spider-dribble"},{"type":"drill","slug":"between-legs-stationary"},{"type":"drill","slug":"v-dribble"},{"type":"drill","slug":"figure-eight-dribble"}]'),
  ('handle-builder', 2, 2, 'Change of Direction', 'Week 2: sharp cuts with the ball', 40, '[{"type":"drill","slug":"weak-hand-stationary"},{"type":"drill","slug":"zig-zag-change-of-direction"},{"type":"drill","slug":"hesitation-series","note":"No cones? Use shoes or water bottles."},{"type":"drill","slug":"weak-hand-full-court"}]'),
  ('handle-builder', 2, 3, 'Two-Ball Rhythm', 'Week 2: same and alternating rhythms', 30, '[{"type":"drill","slug":"two-ball-pound"},{"type":"drill","slug":"two-ball-alternating"},{"type":"drill","slug":"spider-dribble"},{"type":"drill","slug":"full-court-speed-dribble"}]'),
  ('handle-builder', 2, 4, 'Change of Pace to Score', 'Week 2: hesitate, then explode', 40, '[{"type":"drill","slug":"hesitation-series","note":"No cones? Use shoes or water bottles."},{"type":"drill","slug":"in-and-out-attack"},{"type":"drill","slug":"one-dribble-pull-up"},{"type":"drill","slug":"inside-hand-finishes"}]'),
  ('handle-builder', 3, 1, 'Combo Control', 'Week 3: moves behind the back and through the legs', 30, '[{"type":"drill","slug":"spider-dribble"},{"type":"drill","slug":"two-ball-crossover"},{"type":"drill","slug":"behind-the-back-series","note":"No cones? Use shoes or water bottles."},{"type":"drill","slug":"stationary-crossover","note":"Eyes up the whole time"}]'),
  ('handle-builder', 3, 2, 'Attack Moves', 'Week 3: retreat and re-attack', 40, '[{"type":"drill","slug":"retreat-dribble-crossover","note":"No cones? Use shoes or water bottles."},{"type":"drill","slug":"cone-crossover-series"},{"type":"drill","slug":"weak-hand-full-court"},{"type":"drill","slug":"zig-zag-change-of-direction"}]'),
  ('handle-builder', 3, 3, 'Two-Ball Challenge', 'Week 3: coordination and reaction', 35, '[{"type":"drill","slug":"two-ball-alternating"},{"type":"drill","slug":"two-ball-crossover"},{"type":"drill","slug":"tennis-ball-toss-dribble"},{"type":"drill","slug":"full-court-dribble-sprints"}]'),
  ('handle-builder', 3, 4, 'Handle Into Scoring', 'Week 3: finish off change of pace', 50, '[{"type":"drill","slug":"in-and-out-attack"},{"type":"drill","slug":"hesitation-series"},{"type":"drill","slug":"two-dribble-pull-up"},{"type":"drill","slug":"gallop-finish"},{"type":"drill","slug":"floater-series"}]'),
  ('handle-builder', 4, 1, 'Handle Warm-Up Circuit', 'Week 4: full stationary circuit at max speed', 30, '[{"type":"drill","slug":"pound-dribble-series"},{"type":"drill","slug":"spider-dribble"},{"type":"drill","slug":"two-ball-crossover"},{"type":"drill","slug":"behind-the-back-series"},{"type":"note","text":"Newer players: repeat week 3 speeds before adding speed."}]'),
  ('handle-builder', 4, 2, 'Combo Chains', 'Week 4: string moves together', 45, '[{"type":"drill","slug":"combo-move-chain","note":"No cones? Use shoes or water bottles."},{"type":"drill","slug":"retreat-dribble-crossover"},{"type":"drill","slug":"weak-hand-full-court"},{"type":"study","topic_slug":"pnr-reads"}]'),
  ('handle-builder', 4, 3, 'Two-Ball Mastery', 'Week 4: advanced two-ball work', 30, '[{"type":"drill","slug":"two-ball-cone-series"},{"type":"drill","slug":"two-ball-full-court"},{"type":"drill","slug":"tennis-ball-toss-dribble"},{"type":"note","text":"Beginners: stay with Two-Ball Alternating until it feels easy."}]'),
  ('handle-builder', 4, 4, 'Game-Ready Handle', 'Week 4: moves into finishes and pull-ups', 45, '[{"type":"drill","slug":"combo-move-chain"},{"type":"drill","slug":"in-and-out-attack"},{"type":"drill","slug":"two-dribble-pull-up"},{"type":"drill","slug":"off-foot-layups"},{"type":"note","text":"Time a weak-hand full-court trip and compare with week 2."}]'),
  ('finish-at-the-rim', 1, 1, 'Both Hands Around the Rim', 'Week 1: touch and footwork with both hands', 35, '[{"type":"drill","slug":"mikan-drill"},{"type":"drill","slug":"reverse-mikan"},{"type":"drill","slug":"power-layup-series"},{"type":"drill","slug":"weak-hand-layups"},{"type":"drill","slug":"jump-stop-finishes"}]'),
  ('finish-at-the-rim', 1, 2, 'Footwork Foundations', 'Week 1: gather steps and angles', 45, '[{"type":"drill","slug":"one-two-step-vs-hop"},{"type":"drill","slug":"baseline-reverse-layups"},{"type":"drill","slug":"scoop-layup"},{"type":"drill","slug":"inside-hand-finishes"},{"type":"study","topic_slug":"finishing-footwork"}]'),
  ('finish-at-the-rim', 1, 3, 'Finishing on the Move', 'Week 1: layups at speed', 30, '[{"type":"drill","slug":"mikan-drill"},{"type":"drill","slug":"weak-hand-layups"},{"type":"drill","slug":"jump-stop-finishes"},{"type":"drill","slug":"full-court-layup-challenge"},{"type":"note","text":"Count makes in 60 seconds of Mikan. That is your baseline."}]'),
  ('finish-at-the-rim', 2, 1, 'Angles and Touch', 'Week 2: floaters and inside-hand finishes', 35, '[{"type":"drill","slug":"reverse-mikan"},{"type":"drill","slug":"inside-hand-finishes"},{"type":"drill","slug":"floater-series"},{"type":"drill","slug":"off-foot-layups"}]'),
  ('finish-at-the-rim', 2, 2, 'Long Strides and Putbacks', 'Week 2: gallop step and second chances', 40, '[{"type":"drill","slug":"mikan-drill"},{"type":"drill","slug":"gallop-finish"},{"type":"drill","slug":"baseline-reverse-layups"},{"type":"drill","slug":"scoop-layup"},{"type":"drill","slug":"putback-series"}]'),
  ('finish-at-the-rim', 2, 3, 'Body Control', 'Week 2: balance through the finish', 40, '[{"type":"drill","slug":"power-layup-series"},{"type":"drill","slug":"floater-series"},{"type":"drill","slug":"off-foot-layups"},{"type":"drill","slug":"full-court-layup-challenge"},{"type":"exercise","name":"Lateral Bound & Stick","sets":3,"reps":"4 each side"}]'),
  ('finish-at-the-rim', 3, 1, 'Fakes and Finishes', 'Week 3: create space before the finish', 45, '[{"type":"drill","slug":"mikan-drill"},{"type":"drill","slug":"shot-fake-sweep"},{"type":"drill","slug":"gallop-finish"},{"type":"drill","slug":"inside-hand-finishes"},{"type":"drill","slug":"floater-series"}]'),
  ('finish-at-the-rim', 3, 2, 'Finishing Through Contact', 'Week 3: strong, balanced finishes', 40, '[{"type":"drill","slug":"reverse-mikan"},{"type":"drill","slug":"power-layup-series","note":"Chin the ball and imagine contact"},{"type":"drill","slug":"off-foot-layups"},{"type":"drill","slug":"jab-series"},{"type":"drill","slug":"putback-series"}]'),
  ('finish-at-the-rim', 3, 3, 'Explosive Finishes', 'Week 3: two-ball touch and speed', 40, '[{"type":"drill","slug":"two-ball-mikan"},{"type":"drill","slug":"gallop-finish"},{"type":"drill","slug":"floater-series"},{"type":"drill","slug":"full-court-layup-challenge"},{"type":"exercise","name":"Single-Leg Box Jump","sets":3,"reps":"3 each leg"}]'),
  ('finish-at-the-rim', 4, 1, 'Advanced Touch', 'Week 4: finish from any angle', 40, '[{"type":"drill","slug":"two-ball-mikan"},{"type":"drill","slug":"inside-hand-finishes"},{"type":"drill","slug":"off-foot-layups"},{"type":"drill","slug":"catch-and-face-up"},{"type":"drill","slug":"scoop-layup"}]'),
  ('finish-at-the-rim', 4, 2, 'Game-Speed Finishing', 'Week 4: finish at full speed', 35, '[{"type":"drill","slug":"mikan-drill"},{"type":"drill","slug":"gallop-finish"},{"type":"drill","slug":"floater-series"},{"type":"drill","slug":"full-court-layup-challenge"},{"type":"note","text":"Push the pace. Misses at full speed are fine this week."}]'),
  ('finish-at-the-rim', 4, 3, 'Finishing Check-In', 'Week 4: test and review', 35, '[{"type":"drill","slug":"reverse-mikan"},{"type":"drill","slug":"shot-fake-sweep"},{"type":"drill","slug":"floater-series"},{"type":"drill","slug":"off-foot-layups"},{"type":"note","text":"Retest 60 seconds of Mikan and compare with week 1."}]'),
  ('vertical-jump-8-week', 1, 1, 'Baseline Testing', 'Week 1 (Foundation): test standing, approach and broad jump', 35, '[{"type":"note","text":"Warm up 10 minutes first: jog, skips, leg swings and World''s Greatest Stretch."},{"type":"test","test_type":"standing_vertical"},{"type":"test","test_type":"approach_vertical"},{"type":"test","test_type":"standing_broad_jump"},{"type":"exercise","name":"Goblet Squat","sets":3,"reps":"8"},{"type":"exercise","name":"Glute Bridge","sets":3,"reps":"12"},{"type":"exercise","name":"Pogo Hops","sets":3,"reps":"20"}]'),
  ('vertical-jump-8-week', 1, 2, 'Landing Mechanics', 'Week 1 (Foundation): landing and ankle stiffness', 35, '[{"type":"exercise","name":"Snap Downs","sets":3,"reps":"5"},{"type":"exercise","name":"Box Jumps","sets":3,"reps":"5"},{"type":"exercise","name":"Single-Leg Calf Raises","sets":3,"reps":"12 each"},{"type":"exercise","name":"Tibialis Raises","sets":2,"reps":"15"},{"type":"exercise","name":"Front Plank","sets":3,"reps":"30 sec"}]'),
  ('vertical-jump-8-week', 1, 3, 'Strength Base', 'Week 1 (Foundation): single-leg strength', 30, '[{"type":"exercise","name":"Bulgarian Split Squat","sets":3,"reps":"8 each"},{"type":"exercise","name":"Dumbbell Romanian Deadlift","sets":3,"reps":"10"},{"type":"exercise","name":"Broad Jump","sets":3,"reps":"3"},{"type":"exercise","name":"Ankle Dorsiflexion Knee-to-Wall","sets":2,"reps":"10 each"},{"type":"exercise","name":"Couch Stretch (Hip Flexor / Quad)","sets":2,"reps":"60 sec each"}]'),
  ('vertical-jump-8-week', 2, 1, 'Strength and Pop', 'Week 2 (Foundation): max-intent jumps + lower strength', 40, '[{"type":"note","text":"Warm up 10 minutes first: jog, skips, leg swings and World''s Greatest Stretch."},{"type":"exercise","name":"Pogo Hops","sets":3,"reps":"25"},{"type":"exercise","name":"Box Jumps","sets":4,"reps":"4"},{"type":"exercise","name":"Trap Bar Deadlift","sets":4,"reps":"6"},{"type":"exercise","name":"Barbell Hip Thrust","sets":3,"reps":"10"},{"type":"exercise","name":"Single-Leg Calf Raises","sets":3,"reps":"12 each"}]'),
  ('vertical-jump-8-week', 2, 2, 'Lateral Power', 'Week 2 (Foundation): reactive and lateral jumps', 35, '[{"type":"exercise","name":"Snap Downs","sets":3,"reps":"6"},{"type":"exercise","name":"Lateral Bound & Stick","sets":3,"reps":"4 each"},{"type":"exercise","name":"Skater Hops","sets":3,"reps":"6 each"},{"type":"exercise","name":"Nordic Hamstring Curl","sets":3,"reps":"4"},{"type":"exercise","name":"Pallof Press","sets":3,"reps":"10 each"}]'),
  ('vertical-jump-8-week', 2, 3, 'Hinge and Jump', 'Week 2 (Foundation): hip power and hamstrings', 35, '[{"type":"exercise","name":"Broad Jump","sets":4,"reps":"3"},{"type":"exercise","name":"Bulgarian Split Squat","sets":3,"reps":"8 each"},{"type":"exercise","name":"Kettlebell Swing","sets":3,"reps":"10"},{"type":"exercise","name":"Tibialis Raises","sets":3,"reps":"15"},{"type":"exercise","name":"Couch Stretch (Hip Flexor / Quad)","sets":2,"reps":"60 sec each"}]'),
  ('vertical-jump-8-week', 3, 1, 'Heavy Legs, Quick Feet', 'Week 3 (Build): max-intent jumps + lower strength', 40, '[{"type":"note","text":"Warm up 10 minutes first: jog, skips, leg swings and World''s Greatest Stretch."},{"type":"exercise","name":"Pogo Hops","sets":3,"reps":"25"},{"type":"exercise","name":"Hurdle Hops","sets":3,"reps":"5"},{"type":"exercise","name":"Barbell Back Squat","sets":4,"reps":"5"},{"type":"exercise","name":"Barbell Hip Thrust","sets":4,"reps":"8"},{"type":"exercise","name":"Eccentric Heel Drops","sets":3,"reps":"12"}]'),
  ('vertical-jump-8-week', 3, 2, 'Reactive Jumps', 'Week 3 (Build): reactive and lateral jumps', 35, '[{"type":"exercise","name":"Depth Jumps","sets":3,"reps":"3"},{"type":"exercise","name":"Lateral Bound & Stick","sets":3,"reps":"5 each"},{"type":"exercise","name":"Single-Leg Box Jump","sets":3,"reps":"3 each"},{"type":"exercise","name":"Nordic Hamstring Curl","sets":3,"reps":"5"},{"type":"exercise","name":"Dead Bug (Contralateral)","sets":3,"reps":"8 each"}]'),
  ('vertical-jump-8-week', 3, 3, 'Posterior Chain Power', 'Week 3 (Build): hip power and hamstrings', 35, '[{"type":"exercise","name":"Broad Jump","sets":4,"reps":"3"},{"type":"exercise","name":"Trap Bar Deadlift","sets":4,"reps":"5"},{"type":"exercise","name":"Bulgarian Split Squat","sets":3,"reps":"6 each"},{"type":"exercise","name":"Kettlebell Swing","sets":3,"reps":"12"},{"type":"exercise","name":"90/90 Hip Switches","sets":2,"reps":"6 each side"}]'),
  ('vertical-jump-8-week', 4, 1, 'Deload: Easy Pop', 'Week 4 (Deload): low volume, fast and fresh', 20, '[{"type":"note","text":"Deload week: about half the volume. Every rep should feel fast and easy."},{"type":"exercise","name":"Pogo Hops","sets":2,"reps":"15"},{"type":"exercise","name":"Box Jumps","sets":2,"reps":"3"},{"type":"exercise","name":"Goblet Squat","sets":2,"reps":"8"},{"type":"exercise","name":"Glute Bridge","sets":2,"reps":"12"}]'),
  ('vertical-jump-8-week', 4, 2, 'Deload: Ankles and Core', 'Week 4 (Deload): low volume, fast and fresh', 20, '[{"type":"exercise","name":"Snap Downs","sets":2,"reps":"4"},{"type":"exercise","name":"Single-Leg Calf Raises","sets":2,"reps":"10 each"},{"type":"exercise","name":"Tibialis Raises","sets":2,"reps":"15"},{"type":"exercise","name":"Front Plank","sets":2,"reps":"30 sec"}]'),
  ('vertical-jump-8-week', 4, 3, 'Deload: Mobility', 'Week 4 (Deload): low volume, fast and fresh', 20, '[{"type":"exercise","name":"Broad Jump","sets":2,"reps":"3"},{"type":"exercise","name":"Ankle Dorsiflexion Knee-to-Wall","sets":2,"reps":"10 each"},{"type":"exercise","name":"Couch Stretch (Hip Flexor / Quad)","sets":2,"reps":"60 sec each"},{"type":"exercise","name":"World''s Greatest Stretch","sets":2,"reps":"5 each side"},{"type":"note","text":"Sleep and eat well this week. Power phase starts next week."}]'),
  ('vertical-jump-8-week', 5, 1, 'Max Power', 'Week 5 (Power): max-intent jumps + lower strength', 45, '[{"type":"note","text":"Warm up 10 minutes first: jog, skips, leg swings and World''s Greatest Stretch."},{"type":"exercise","name":"Depth Jumps","sets":4,"reps":"3"},{"type":"exercise","name":"Approach Vertical Jump","sets":4,"reps":"3"},{"type":"exercise","name":"Trap Bar Deadlift","sets":5,"reps":"3"},{"type":"exercise","name":"Barbell Hip Thrust","sets":3,"reps":"6"},{"type":"exercise","name":"Single-Leg Calf Raises","sets":3,"reps":"10 each"}]'),
  ('vertical-jump-8-week', 5, 2, 'Elastic Bounds', 'Week 5 (Power): reactive and lateral jumps', 35, '[{"type":"exercise","name":"Hurdle Hops","sets":4,"reps":"5"},{"type":"exercise","name":"Alternate-Leg Bounds","sets":3,"reps":"6 each"},{"type":"exercise","name":"Tuck Jumps","sets":3,"reps":"5"},{"type":"exercise","name":"Nordic Hamstring Curl","sets":3,"reps":"5"},{"type":"exercise","name":"Pallof Press","sets":3,"reps":"10 each"}]'),
  ('vertical-jump-8-week', 5, 3, 'Explosive Triple Extension', 'Week 5 (Power): hip power and hamstrings', 35, '[{"type":"exercise","name":"Barbell Hang Power Clean","sets":4,"reps":"3"},{"type":"exercise","name":"Split Squat Jumps","sets":3,"reps":"4 each"},{"type":"exercise","name":"Bulgarian Split Squat","sets":3,"reps":"6 each"},{"type":"exercise","name":"Rim Touches","sets":3,"reps":"8"},{"type":"exercise","name":"Eccentric Heel Drops","sets":3,"reps":"12"}]'),
  ('vertical-jump-8-week', 6, 1, 'Heavy and Fast', 'Week 6 (Power): max-intent jumps + lower strength', 35, '[{"type":"note","text":"Warm up 10 minutes first: jog, skips, leg swings and World''s Greatest Stretch."},{"type":"exercise","name":"Depth Jumps","sets":4,"reps":"4"},{"type":"exercise","name":"Approach Vertical Jump","sets":4,"reps":"3"},{"type":"exercise","name":"Barbell Back Squat","sets":5,"reps":"3"},{"type":"exercise","name":"Single-Leg Calf Raises","sets":3,"reps":"10 each"}]'),
  ('vertical-jump-8-week', 6, 2, 'Single-Leg Power', 'Week 6 (Power): reactive and lateral jumps', 35, '[{"type":"exercise","name":"Hurdle Hops","sets":4,"reps":"6"},{"type":"exercise","name":"Single-Leg Box Jump","sets":3,"reps":"4 each"},{"type":"exercise","name":"Lateral Bound & Stick","sets":3,"reps":"5 each"},{"type":"exercise","name":"Tuck Jumps","sets":3,"reps":"6"},{"type":"exercise","name":"Hanging Leg Raises","sets":3,"reps":"8"}]'),
  ('vertical-jump-8-week', 6, 3, 'Clean and Reach', 'Week 6 (Power): hip power and hamstrings', 40, '[{"type":"exercise","name":"Barbell Hang Power Clean","sets":4,"reps":"3"},{"type":"exercise","name":"Split Squat Jumps","sets":3,"reps":"5 each"},{"type":"exercise","name":"Trap Bar Deadlift","sets":4,"reps":"3"},{"type":"exercise","name":"Rim Touches","sets":3,"reps":"10"},{"type":"exercise","name":"Tibialis Raises","sets":3,"reps":"15"}]'),
  ('vertical-jump-8-week', 7, 1, 'Peak Power', 'Week 7 (Peak power): max-intent jumps + lower strength', 40, '[{"type":"note","text":"Warm up 10 minutes first: jog, skips, leg swings and World''s Greatest Stretch."},{"type":"exercise","name":"Depth Jumps","sets":5,"reps":"3"},{"type":"exercise","name":"Approach Vertical Jump","sets":5,"reps":"3"},{"type":"exercise","name":"Trap Bar Deadlift","sets":4,"reps":"2"},{"type":"exercise","name":"Barbell Hip Thrust","sets":3,"reps":"6"}]'),
  ('vertical-jump-8-week', 7, 2, 'Bounds and Hops', 'Week 7 (Peak power): reactive and lateral jumps', 40, '[{"type":"exercise","name":"Hurdle Hops","sets":4,"reps":"5"},{"type":"exercise","name":"Alternate-Leg Bounds","sets":4,"reps":"5 each"},{"type":"exercise","name":"Single-Leg Box Jump","sets":3,"reps":"3 each"},{"type":"exercise","name":"Nordic Hamstring Curl","sets":3,"reps":"5"},{"type":"exercise","name":"Pallof Press","sets":3,"reps":"10 each"}]'),
  ('vertical-jump-8-week', 7, 3, 'Speed-Strength', 'Week 7 (Peak power): hip power and hamstrings', 40, '[{"type":"exercise","name":"Barbell Hang Power Clean","sets":5,"reps":"2"},{"type":"exercise","name":"Rim Touches","sets":4,"reps":"8"},{"type":"exercise","name":"Split Squat Jumps","sets":3,"reps":"4 each"},{"type":"exercise","name":"Eccentric Heel Drops","sets":3,"reps":"12"},{"type":"exercise","name":"90/90 Hip Switches","sets":2,"reps":"6 each side"}]'),
  ('vertical-jump-8-week', 8, 1, 'Taper: Stay Sharp', 'Week 8 (Taper and retest): low volume, fast and fresh', 25, '[{"type":"note","text":"Taper week: low volume, full intent. Stay fresh for the retest."},{"type":"exercise","name":"Pogo Hops","sets":2,"reps":"15"},{"type":"exercise","name":"Depth Jumps","sets":3,"reps":"2"},{"type":"exercise","name":"Approach Vertical Jump","sets":3,"reps":"2"},{"type":"exercise","name":"Trap Bar Deadlift","sets":3,"reps":"2"}]'),
  ('vertical-jump-8-week', 8, 2, 'Taper: Prime the Legs', 'Week 8 (Taper and retest): low volume, fast and fresh', 25, '[{"type":"exercise","name":"Snap Downs","sets":2,"reps":"4"},{"type":"exercise","name":"Box Jumps","sets":3,"reps":"3"},{"type":"exercise","name":"Single-Leg Calf Raises","sets":2,"reps":"10 each"},{"type":"exercise","name":"World''s Greatest Stretch","sets":2,"reps":"5 each side"}]'),
  ('vertical-jump-8-week', 8, 3, 'Retest Day', 'Week 8 (Taper and retest): retest all jumps', 20, '[{"type":"note","text":"Warm up 10 minutes first: jog, skips, leg swings and World''s Greatest Stretch."},{"type":"exercise","name":"Pogo Hops","sets":2,"reps":"10"},{"type":"test","test_type":"standing_vertical"},{"type":"test","test_type":"approach_vertical"},{"type":"test","test_type":"standing_broad_jump"},{"type":"note","text":"Compare with your week 1 numbers. Rest 2-3 minutes between max attempts."}]'),
  ('guard-offseason', 1, 1, 'Handle and Lower Strength', 'Week 1 (Base): tight handle into pull-ups + leg strength', 45, '[{"type":"drill","slug":"pound-dribble-series"},{"type":"drill","slug":"hesitation-series","note":"No cones? Use shoes or water bottles."},{"type":"drill","slug":"one-dribble-pull-up"},{"type":"exercise","name":"Goblet Squat","sets":3,"reps":"8"},{"type":"exercise","name":"Reverse Lunge","sets":3,"reps":"8 each"},{"type":"exercise","name":"Lateral Band Walk","sets":2,"reps":"12 each way"}]'),
  ('guard-offseason', 1, 2, 'Shooting and Core', 'Week 1 (Base): catch-and-shoot and shot fakes + core stability', 45, '[{"type":"drill","slug":"spin-out-catch-and-shoot"},{"type":"drill","slug":"shot-fake-one-dribble"},{"type":"drill","slug":"ten-in-a-row-free-throws"},{"type":"exercise","name":"Dead Bug (Contralateral)","sets":3,"reps":"8 each"},{"type":"exercise","name":"Banded Shoulder External Rotation","sets":2,"reps":"15"}]'),
  ('guard-offseason', 1, 3, 'Finishing and Explosiveness', 'Week 1 (Base): finishes with both hands + plyometrics', 35, '[{"type":"drill","slug":"mikan-drill"},{"type":"drill","slug":"power-layup-series"},{"type":"drill","slug":"weak-hand-layups"},{"type":"exercise","name":"Pogo Hops","sets":3,"reps":"20"},{"type":"exercise","name":"Push-Ups (Tempo)","sets":3,"reps":"10"}]'),
  ('guard-offseason', 1, 4, 'Game Speed and Conditioning', 'Week 1 (Base): shots and defense at game pace', 50, '[{"type":"test","test_type":"pro_agility_5_10_5"},{"type":"drill","slug":"full-court-speed-dribble"},{"type":"drill","slug":"around-the-world"},{"type":"drill","slug":"lane-slides"},{"type":"exercise","name":"Single-Leg Balance Reach","sets":2,"reps":"8 each"},{"type":"exercise","name":"World''s Greatest Stretch","sets":2,"reps":"5 each side"},{"type":"study","topic_slug":"pnr-reads"}]'),
  ('guard-offseason', 2, 1, 'Handle and Lower Strength', 'Week 2 (Base): tight handle into pull-ups + leg strength', 50, '[{"type":"drill","slug":"spider-dribble"},{"type":"drill","slug":"in-and-out-attack"},{"type":"drill","slug":"one-dribble-pull-up"},{"type":"exercise","name":"Goblet Squat","sets":4,"reps":"8"},{"type":"exercise","name":"Reverse Lunge","sets":3,"reps":"10 each"},{"type":"exercise","name":"Lateral Band Walk","sets":3,"reps":"12 each way"}]'),
  ('guard-offseason', 2, 2, 'Shooting and Core', 'Week 2 (Base): catch-and-shoot and shot fakes + core stability', 45, '[{"type":"drill","slug":"five-spot-threes"},{"type":"drill","slug":"shot-fake-one-dribble"},{"type":"drill","slug":"ten-in-a-row-free-throws"},{"type":"exercise","name":"Pallof Press","sets":3,"reps":"10 each"},{"type":"exercise","name":"Banded Shoulder External Rotation","sets":2,"reps":"15"}]'),
  ('guard-offseason', 2, 3, 'Finishing and Explosiveness', 'Week 2 (Base): finishes with both hands + plyometrics', 40, '[{"type":"drill","slug":"reverse-mikan"},{"type":"drill","slug":"inside-hand-finishes"},{"type":"drill","slug":"floater-series"},{"type":"exercise","name":"Box Jumps","sets":3,"reps":"5"},{"type":"exercise","name":"Inverted Row","sets":3,"reps":"10"}]'),
  ('guard-offseason', 2, 4, 'Game Speed and Conditioning', 'Week 2 (Base): shots and defense at game pace', 55, '[{"type":"drill","slug":"transition-pull-ups"},{"type":"drill","slug":"beat-the-pro"},{"type":"drill","slug":"defensive-slide-intervals"},{"type":"exercise","name":"Single-Leg Balance Reach","sets":3,"reps":"8 each"},{"type":"exercise","name":"World''s Greatest Stretch","sets":2,"reps":"5 each side"},{"type":"study","topic_slug":"transition"}]'),
  ('guard-offseason', 3, 1, 'Handle and Lower Strength', 'Week 3 (Build): tight handle into pull-ups + leg strength', 55, '[{"type":"drill","slug":"two-ball-alternating"},{"type":"drill","slug":"retreat-dribble-crossover"},{"type":"drill","slug":"two-dribble-pull-up"},{"type":"exercise","name":"Trap Bar Deadlift","sets":4,"reps":"6"},{"type":"exercise","name":"Bulgarian Split Squat","sets":3,"reps":"8 each"},{"type":"exercise","name":"Copenhagen Plank","sets":3,"reps":"20 sec each"}]'),
  ('guard-offseason', 3, 2, 'Shooting and Core', 'Week 3 (Build): catch-and-shoot and shot fakes + core stability', 50, '[{"type":"drill","slug":"five-spot-threes"},{"type":"drill","slug":"side-step-three"},{"type":"drill","slug":"tired-legs-free-throws"},{"type":"exercise","name":"Side Plank","sets":3,"reps":"30 sec each"},{"type":"exercise","name":"Banded Shoulder External Rotation","sets":3,"reps":"12"}]'),
  ('guard-offseason', 3, 3, 'Finishing and Explosiveness', 'Week 3 (Build): finishes with both hands + plyometrics', 40, '[{"type":"drill","slug":"mikan-drill"},{"type":"drill","slug":"floater-series"},{"type":"drill","slug":"off-foot-layups"},{"type":"exercise","name":"Lateral Bound & Stick","sets":3,"reps":"4 each"},{"type":"exercise","name":"Single-Arm Dumbbell Row","sets":3,"reps":"10 each"}]'),
  ('guard-offseason', 3, 4, 'Game Speed and Conditioning', 'Week 3 (Build): shots and defense at game pace', 55, '[{"type":"drill","slug":"transition-pull-ups"},{"type":"drill","slug":"thirty-one"},{"type":"drill","slug":"slide-turn-sprint"},{"type":"exercise","name":"Tibialis Raises","sets":3,"reps":"15"},{"type":"exercise","name":"90/90 Hip Switches","sets":2,"reps":"6 each side"},{"type":"study","topic_slug":"ball-handling"}]'),
  ('guard-offseason', 4, 1, 'Handle and Lower Strength', 'Week 4 (Build): tight handle into pull-ups + leg strength', 55, '[{"type":"drill","slug":"two-ball-crossover"},{"type":"drill","slug":"cone-crossover-series"},{"type":"drill","slug":"two-dribble-pull-up"},{"type":"exercise","name":"Trap Bar Deadlift","sets":4,"reps":"5"},{"type":"exercise","name":"Bulgarian Split Squat","sets":4,"reps":"8 each"},{"type":"exercise","name":"Copenhagen Plank","sets":3,"reps":"25 sec each"}]'),
  ('guard-offseason', 4, 2, 'Shooting and Core', 'Week 4 (Build): catch-and-shoot and shot fakes + core stability', 45, '[{"type":"drill","slug":"drift-and-relocate"},{"type":"drill","slug":"side-step-three"},{"type":"drill","slug":"tired-legs-free-throws"},{"type":"exercise","name":"Stir the Pot","sets":3,"reps":"8 each way"},{"type":"exercise","name":"Prone Y-T-W Raises","sets":2,"reps":"8 each"}]'),
  ('guard-offseason', 4, 3, 'Finishing and Explosiveness', 'Week 4 (Build): finishes with both hands + plyometrics', 40, '[{"type":"drill","slug":"reverse-mikan"},{"type":"drill","slug":"gallop-finish"},{"type":"drill","slug":"inside-hand-finishes"},{"type":"exercise","name":"Skater Hops","sets":3,"reps":"6 each"},{"type":"exercise","name":"Dumbbell Floor Press","sets":3,"reps":"8"}]'),
  ('guard-offseason', 4, 4, 'Game Speed and Conditioning', 'Week 4 (Build): shots and defense at game pace', 55, '[{"type":"drill","slug":"sprint-and-shoot-intervals"},{"type":"drill","slug":"beat-the-pro"},{"type":"drill","slug":"slide-turn-sprint"},{"type":"exercise","name":"Tibialis Raises","sets":3,"reps":"20"},{"type":"exercise","name":"90/90 Hip Switches","sets":2,"reps":"6 each side"},{"type":"study","topic_slug":"game-situations"}]'),
  ('guard-offseason', 5, 1, 'Handle and Lower Strength', 'Week 5 (Game speed): tight handle into pull-ups + leg strength', 60, '[{"type":"drill","slug":"behind-the-back-series"},{"type":"drill","slug":"combo-move-chain"},{"type":"drill","slug":"step-back-jumper"},{"type":"exercise","name":"Trap Bar Deadlift","sets":5,"reps":"4"},{"type":"exercise","name":"Bulgarian Split Squat","sets":4,"reps":"6 each"},{"type":"exercise","name":"Nordic Hamstring Curl","sets":3,"reps":"4"}]'),
  ('guard-offseason', 5, 2, 'Shooting and Core', 'Week 5 (Game speed): catch-and-shoot and shot fakes + core stability', 55, '[{"type":"drill","slug":"sprint-back-threes"},{"type":"drill","slug":"side-step-three"},{"type":"drill","slug":"free-throw-pressure-ladder"},{"type":"exercise","name":"Pallof Press","sets":3,"reps":"12 each"},{"type":"exercise","name":"Prone Y-T-W Raises","sets":3,"reps":"8 each"}]'),
  ('guard-offseason', 5, 3, 'Finishing and Explosiveness', 'Week 5 (Game speed): finishes with both hands + plyometrics', 40, '[{"type":"drill","slug":"mikan-drill"},{"type":"drill","slug":"off-foot-layups"},{"type":"drill","slug":"floater-series"},{"type":"exercise","name":"Depth Jumps","sets":3,"reps":"4"},{"type":"exercise","name":"Neutral Grip Pull-Ups","sets":3,"reps":"6"}]'),
  ('guard-offseason', 5, 4, 'Game Speed and Conditioning', 'Week 5 (Game speed): shots and defense at game pace', 55, '[{"type":"drill","slug":"sprint-and-shoot-intervals"},{"type":"drill","slug":"game-winner-countdown"},{"type":"drill","slug":"closeout-sprint-series"},{"type":"exercise","name":"Eccentric Heel Drops","sets":3,"reps":"12"},{"type":"exercise","name":"Couch Stretch (Hip Flexor / Quad)","sets":2,"reps":"60 sec each"},{"type":"study","topic_slug":"film-study"}]'),
  ('guard-offseason', 6, 1, 'Handle and Lower Strength', 'Week 6 (Game speed): tight handle into pull-ups + leg strength', 55, '[{"type":"drill","slug":"two-ball-cone-series"},{"type":"drill","slug":"combo-move-chain"},{"type":"drill","slug":"step-back-jumper"},{"type":"exercise","name":"Trap Bar Deadlift","sets":3,"reps":"3"},{"type":"exercise","name":"Bulgarian Split Squat","sets":3,"reps":"6 each"},{"type":"exercise","name":"Nordic Hamstring Curl","sets":3,"reps":"5"}]'),
  ('guard-offseason', 6, 2, 'Shooting and Core', 'Week 6 (Game speed): catch-and-shoot and shot fakes + core stability', 50, '[{"type":"drill","slug":"sprint-back-threes"},{"type":"drill","slug":"step-back-jumper"},{"type":"drill","slug":"free-throw-pressure-ladder"},{"type":"exercise","name":"Hanging Leg Raises","sets":3,"reps":"8"},{"type":"exercise","name":"Prone Y-T-W Raises","sets":2,"reps":"8 each"}]'),
  ('guard-offseason', 6, 3, 'Finishing and Explosiveness', 'Week 6 (Game speed): finishes with both hands + plyometrics', 35, '[{"type":"drill","slug":"reverse-mikan"},{"type":"drill","slug":"two-ball-mikan"},{"type":"drill","slug":"gallop-finish"},{"type":"exercise","name":"Approach Vertical Jump","sets":3,"reps":"3"},{"type":"exercise","name":"Overhead Dumbbell Push Press","sets":3,"reps":"5"}]'),
  ('guard-offseason', 6, 4, 'Game Speed and Conditioning', 'Week 6 (Game speed): shots and defense at game pace', 55, '[{"type":"test","test_type":"pro_agility_5_10_5"},{"type":"drill","slug":"ball-line-drills"},{"type":"drill","slug":"game-winner-countdown"},{"type":"drill","slug":"closeout-sprint-series"},{"type":"exercise","name":"Eccentric Heel Drops","sets":3,"reps":"12"},{"type":"exercise","name":"Couch Stretch (Hip Flexor / Quad)","sets":2,"reps":"60 sec each"},{"type":"study","topic_slug":"mental-game"}]'),
  ('wing-offseason', 1, 1, 'Catch-and-Shoot and Lower Strength', 'Week 1 (Base): shot-ready footwork + leg strength', 45, '[{"type":"drill","slug":"triple-threat-stance"},{"type":"drill","slug":"spin-out-catch-and-shoot"},{"type":"drill","slug":"hop-vs-one-two-shooting"},{"type":"exercise","name":"Goblet Squat","sets":3,"reps":"8"},{"type":"exercise","name":"Dumbbell Romanian Deadlift","sets":3,"reps":"10"},{"type":"exercise","name":"Lateral Lunge","sets":3,"reps":"8 each"}]'),
  ('wing-offseason', 1, 2, 'Attack Closeouts', 'Week 1 (Base): shot fakes, drives and finishes + core', 50, '[{"type":"drill","slug":"shot-fake-one-dribble"},{"type":"drill","slug":"power-layup-series"},{"type":"drill","slug":"weak-hand-layups"},{"type":"exercise","name":"Pallof Press","sets":3,"reps":"10 each"},{"type":"exercise","name":"Push-Ups (Tempo)","sets":3,"reps":"10"},{"type":"study","topic_slug":"spacing-off-ball"}]'),
  ('wing-offseason', 1, 3, 'Defense and Explosiveness', 'Week 1 (Base): slides, closeouts and rebounding + plyometrics', 35, '[{"type":"drill","slug":"defensive-stance-holds"},{"type":"drill","slug":"closeout-fundamentals"},{"type":"drill","slug":"toss-rebound-chin"},{"type":"exercise","name":"Pogo Hops","sets":3,"reps":"20"},{"type":"exercise","name":"Single-Leg Calf Raises","sets":3,"reps":"12 each"}]'),
  ('wing-offseason', 1, 4, 'Game-Speed Shooting', 'Week 1 (Base): shots on the run and free throws under fatigue', 45, '[{"type":"test","test_type":"lane_agility"},{"type":"drill","slug":"full-court-layup-challenge"},{"type":"drill","slug":"around-the-world"},{"type":"drill","slug":"ten-in-a-row-free-throws"},{"type":"exercise","name":"Single-Leg Balance Reach","sets":2,"reps":"8 each"},{"type":"exercise","name":"World''s Greatest Stretch","sets":2,"reps":"5 each side"}]'),
  ('wing-offseason', 2, 1, 'Catch-and-Shoot and Lower Strength', 'Week 2 (Base): shot-ready footwork + leg strength', 55, '[{"type":"drill","slug":"jab-series"},{"type":"drill","slug":"corner-three-series"},{"type":"drill","slug":"spin-out-catch-and-shoot"},{"type":"exercise","name":"Goblet Squat","sets":4,"reps":"8"},{"type":"exercise","name":"Dumbbell Romanian Deadlift","sets":3,"reps":"10"},{"type":"exercise","name":"Lateral Lunge","sets":3,"reps":"10 each"}]'),
  ('wing-offseason', 2, 2, 'Attack Closeouts', 'Week 2 (Base): shot fakes, drives and finishes + core', 45, '[{"type":"drill","slug":"one-dribble-pull-up"},{"type":"drill","slug":"inside-hand-finishes"},{"type":"drill","slug":"hesitation-series","note":"No cones? Use shoes or water bottles."},{"type":"exercise","name":"Dead Bug (Contralateral)","sets":3,"reps":"8 each"},{"type":"exercise","name":"Inverted Row","sets":3,"reps":"10"}]'),
  ('wing-offseason', 2, 3, 'Defense and Explosiveness', 'Week 2 (Base): slides, closeouts and rebounding + plyometrics', 35, '[{"type":"drill","slug":"lane-slides"},{"type":"drill","slug":"zig-zag-slides"},{"type":"drill","slug":"superman-rebounding"},{"type":"exercise","name":"Box Jumps","sets":3,"reps":"5"},{"type":"exercise","name":"Single-Leg Calf Raises","sets":3,"reps":"15 each"}]'),
  ('wing-offseason', 2, 4, 'Game-Speed Shooting', 'Week 2 (Base): shots on the run and free throws under fatigue', 55, '[{"type":"drill","slug":"transition-pull-ups"},{"type":"drill","slug":"beat-the-pro"},{"type":"drill","slug":"tired-legs-free-throws"},{"type":"exercise","name":"Single-Leg Balance Reach","sets":3,"reps":"8 each"},{"type":"exercise","name":"Couch Stretch (Hip Flexor / Quad)","sets":2,"reps":"60 sec each"},{"type":"study","topic_slug":"defense-rotations"}]'),
  ('wing-offseason', 3, 1, 'Catch-and-Shoot and Lower Strength', 'Week 3 (Build): shot-ready footwork + leg strength', 55, '[{"type":"drill","slug":"shot-fake-sweep"},{"type":"drill","slug":"five-spot-threes"},{"type":"drill","slug":"drift-and-relocate"},{"type":"exercise","name":"Barbell Front Squat","sets":4,"reps":"6"},{"type":"exercise","name":"Single-Leg Romanian Deadlift","sets":3,"reps":"8 each"},{"type":"exercise","name":"Lateral Bound & Stick","sets":3,"reps":"4 each"}]'),
  ('wing-offseason', 3, 2, 'Attack Closeouts', 'Week 3 (Build): shot fakes, drives and finishes + core', 55, '[{"type":"drill","slug":"shot-fake-one-dribble"},{"type":"drill","slug":"gallop-finish"},{"type":"drill","slug":"in-and-out-attack"},{"type":"exercise","name":"Side Plank","sets":3,"reps":"30 sec each"},{"type":"exercise","name":"Dumbbell Floor Press","sets":3,"reps":"8"},{"type":"study","topic_slug":"finishing-footwork"}]'),
  ('wing-offseason', 3, 3, 'Defense and Explosiveness', 'Week 3 (Build): slides, closeouts and rebounding + plyometrics', 40, '[{"type":"drill","slug":"slide-turn-sprint"},{"type":"drill","slug":"help-and-recover"},{"type":"drill","slug":"toss-rebound-chin"},{"type":"exercise","name":"Broad Jump","sets":4,"reps":"3"},{"type":"exercise","name":"Tibialis Raises","sets":3,"reps":"15"}]'),
  ('wing-offseason', 3, 4, 'Game-Speed Shooting', 'Week 3 (Build): shots on the run and free throws under fatigue', 45, '[{"type":"drill","slug":"transition-pull-ups"},{"type":"drill","slug":"thirty-one"},{"type":"drill","slug":"ten-in-a-row-free-throws"},{"type":"exercise","name":"Single-Leg Balance Reach","sets":3,"reps":"10 each"},{"type":"exercise","name":"World''s Greatest Stretch","sets":2,"reps":"5 each side"}]'),
  ('wing-offseason', 4, 1, 'Catch-and-Shoot and Lower Strength', 'Week 4 (Build): shot-ready footwork + leg strength', 55, '[{"type":"drill","slug":"jab-series"},{"type":"drill","slug":"drift-and-relocate"},{"type":"drill","slug":"corner-three-series"},{"type":"exercise","name":"Barbell Front Squat","sets":4,"reps":"5"},{"type":"exercise","name":"Single-Leg Romanian Deadlift","sets":3,"reps":"8 each"},{"type":"exercise","name":"Lateral Bound & Stick","sets":3,"reps":"5 each"}]'),
  ('wing-offseason', 4, 2, 'Attack Closeouts', 'Week 4 (Build): shot fakes, drives and finishes + core', 45, '[{"type":"drill","slug":"two-dribble-pull-up"},{"type":"drill","slug":"floater-series"},{"type":"drill","slug":"retreat-dribble-crossover"},{"type":"exercise","name":"Medicine Ball Rotational Scoop Toss","sets":3,"reps":"6 each"},{"type":"exercise","name":"Single-Arm Dumbbell Row","sets":3,"reps":"10 each"}]'),
  ('wing-offseason', 4, 3, 'Defense and Explosiveness', 'Week 4 (Build): slides, closeouts and rebounding + plyometrics', 40, '[{"type":"drill","slug":"help-and-recover"},{"type":"drill","slug":"slide-turn-sprint"},{"type":"drill","slug":"superman-rebounding"},{"type":"exercise","name":"Hurdle Hops","sets":3,"reps":"5"},{"type":"exercise","name":"Tibialis Raises","sets":3,"reps":"20"}]'),
  ('wing-offseason', 4, 4, 'Game-Speed Shooting', 'Week 4 (Build): shots on the run and free throws under fatigue', 65, '[{"type":"drill","slug":"sprint-and-shoot-intervals"},{"type":"drill","slug":"hundred-makes-challenge"},{"type":"drill","slug":"tired-legs-free-throws"},{"type":"exercise","name":"Copenhagen Plank","sets":3,"reps":"20 sec each"},{"type":"exercise","name":"Couch Stretch (Hip Flexor / Quad)","sets":2,"reps":"60 sec each"},{"type":"study","topic_slug":"transition"}]'),
  ('wing-offseason', 5, 1, 'Catch-and-Shoot and Lower Strength', 'Week 5 (Game speed): shot-ready footwork + leg strength', 55, '[{"type":"drill","slug":"catch-and-face-up"},{"type":"drill","slug":"sprint-back-threes"},{"type":"drill","slug":"drift-and-relocate"},{"type":"exercise","name":"Trap Bar Deadlift","sets":4,"reps":"4"},{"type":"exercise","name":"Nordic Hamstring Curl","sets":3,"reps":"4"},{"type":"exercise","name":"Skater Hops","sets":3,"reps":"6 each"}]'),
  ('wing-offseason', 5, 2, 'Attack Closeouts', 'Week 5 (Game speed): shot fakes, drives and finishes + core', 55, '[{"type":"drill","slug":"two-dribble-pull-up"},{"type":"drill","slug":"off-foot-layups"},{"type":"drill","slug":"combo-move-chain"},{"type":"exercise","name":"Hanging Leg Raises","sets":3,"reps":"8"},{"type":"exercise","name":"Neutral Grip Pull-Ups","sets":3,"reps":"6"},{"type":"study","topic_slug":"film-study"}]'),
  ('wing-offseason', 5, 3, 'Defense and Explosiveness', 'Week 5 (Game speed): slides, closeouts and rebounding + plyometrics', 40, '[{"type":"drill","slug":"closeout-sprint-series"},{"type":"drill","slug":"slide-turn-sprint"},{"type":"drill","slug":"putback-series"},{"type":"exercise","name":"Depth Jumps","sets":3,"reps":"4"},{"type":"exercise","name":"Eccentric Heel Drops","sets":3,"reps":"12"}]'),
  ('wing-offseason', 5, 4, 'Game-Speed Shooting', 'Week 5 (Game speed): shots on the run and free throws under fatigue', 45, '[{"type":"drill","slug":"sprint-and-shoot-intervals"},{"type":"drill","slug":"game-winner-countdown"},{"type":"drill","slug":"free-throw-pressure-ladder"},{"type":"exercise","name":"Copenhagen Plank","sets":3,"reps":"25 sec each"},{"type":"exercise","name":"90/90 Hip Switches","sets":2,"reps":"6 each side"}]'),
  ('wing-offseason', 6, 1, 'Catch-and-Shoot and Lower Strength', 'Week 6 (Game speed): shot-ready footwork + leg strength', 55, '[{"type":"drill","slug":"shot-fake-sweep"},{"type":"drill","slug":"side-step-three"},{"type":"drill","slug":"sprint-back-threes"},{"type":"exercise","name":"Trap Bar Deadlift","sets":3,"reps":"3"},{"type":"exercise","name":"Nordic Hamstring Curl","sets":3,"reps":"5"},{"type":"exercise","name":"Skater Hops","sets":3,"reps":"6 each"}]'),
  ('wing-offseason', 6, 2, 'Attack Closeouts', 'Week 6 (Game speed): shot fakes, drives and finishes + core', 50, '[{"type":"drill","slug":"step-back-jumper"},{"type":"drill","slug":"floater-series"},{"type":"drill","slug":"combo-move-chain"},{"type":"exercise","name":"Medicine Ball Rotational Scoop Toss","sets":4,"reps":"5 each"},{"type":"exercise","name":"Overhead Dumbbell Push Press","sets":3,"reps":"5"}]'),
  ('wing-offseason', 6, 3, 'Defense and Explosiveness', 'Week 6 (Game speed): slides, closeouts and rebounding + plyometrics', 40, '[{"type":"drill","slug":"closeout-sprint-series"},{"type":"drill","slug":"help-and-recover"},{"type":"drill","slug":"putback-series"},{"type":"exercise","name":"Approach Vertical Jump","sets":3,"reps":"3"},{"type":"exercise","name":"Single-Leg Calf Raises","sets":2,"reps":"12 each"}]'),
  ('wing-offseason', 6, 4, 'Game-Speed Shooting', 'Week 6 (Game speed): shots on the run and free throws under fatigue', 60, '[{"type":"test","test_type":"lane_agility"},{"type":"drill","slug":"sprint-and-shoot-intervals"},{"type":"drill","slug":"game-winner-countdown"},{"type":"drill","slug":"free-throw-pressure-ladder"},{"type":"exercise","name":"Copenhagen Plank","sets":2,"reps":"20 sec each"},{"type":"exercise","name":"90/90 Hip Switches","sets":2,"reps":"6 each side"},{"type":"study","topic_slug":"mental-game"}]'),
  ('big-development', 1, 1, 'Post Moves and Lower Strength', 'Week 1 (Base): post footwork and finishing + leg strength', 45, '[{"type":"drill","slug":"mikan-drill"},{"type":"drill","slug":"drop-step-series"},{"type":"drill","slug":"jump-hook"},{"type":"exercise","name":"Goblet Squat","sets":3,"reps":"8"},{"type":"exercise","name":"Glute Bridge","sets":3,"reps":"12"},{"type":"exercise","name":"Farmer''s Carry","sets":3,"reps":"30 m"}]'),
  ('big-development', 1, 2, 'Rebounding and Touch', 'Week 1 (Base): secure the ball and finish soft + upper strength', 45, '[{"type":"drill","slug":"toss-rebound-chin"},{"type":"drill","slug":"power-layup-series"},{"type":"drill","slug":"form-shooting-one-hand"},{"type":"exercise","name":"Push-Ups (Tempo)","sets":3,"reps":"10"},{"type":"exercise","name":"Inverted Row","sets":3,"reps":"10"},{"type":"study","topic_slug":"post-play"}]'),
  ('big-development', 1, 3, 'Face-Up Game and Power', 'Week 1 (Base): face-up moves and shooting range + plyometrics', 40, '[{"type":"drill","slug":"pivot-series"},{"type":"drill","slug":"jump-stop-landings"},{"type":"drill","slug":"free-throw-routine-builder"},{"type":"exercise","name":"Box Jumps","sets":3,"reps":"5"},{"type":"exercise","name":"Front Plank","sets":3,"reps":"40 sec"}]'),
  ('big-development', 1, 4, 'Defense and Conditioning', 'Week 1 (Base): defensive footwork and finishing tired', 35, '[{"type":"test","test_type":"standing_vertical"},{"type":"drill","slug":"defensive-stance-holds"},{"type":"drill","slug":"sprint-backpedal-transitions"},{"type":"drill","slug":"power-layup-series","note":"Finish these moves tired, right after the sprints"},{"type":"exercise","name":"Tibialis Raises","sets":2,"reps":"15"},{"type":"exercise","name":"Deep Squat Hold","sets":2,"reps":"45 sec"}]'),
  ('big-development', 2, 1, 'Post Moves and Lower Strength', 'Week 2 (Base): post footwork and finishing + leg strength', 45, '[{"type":"drill","slug":"reverse-mikan"},{"type":"drill","slug":"drop-step-series"},{"type":"drill","slug":"jump-hook"},{"type":"exercise","name":"Goblet Squat","sets":4,"reps":"8"},{"type":"exercise","name":"Barbell Hip Thrust","sets":3,"reps":"10"},{"type":"exercise","name":"Farmer''s Carry","sets":3,"reps":"40 m"}]'),
  ('big-development', 2, 2, 'Rebounding and Touch', 'Week 2 (Base): secure the ball and finish soft + upper strength', 40, '[{"type":"drill","slug":"backboard-tips"},{"type":"drill","slug":"bank-shot-series"},{"type":"drill","slug":"form-shooting-ladder"},{"type":"exercise","name":"Dumbbell Bench Press","sets":3,"reps":"10"},{"type":"exercise","name":"Single-Arm Dumbbell Row","sets":3,"reps":"10 each"}]'),
  ('big-development', 2, 3, 'Face-Up Game and Power', 'Week 2 (Base): face-up moves and shooting range + plyometrics', 45, '[{"type":"drill","slug":"catch-and-face-up"},{"type":"drill","slug":"shot-fake-one-dribble"},{"type":"drill","slug":"five-spot-midrange"},{"type":"exercise","name":"Box Jumps","sets":4,"reps":"5"},{"type":"exercise","name":"Pallof Press","sets":3,"reps":"10 each"}]'),
  ('big-development', 2, 4, 'Defense and Conditioning', 'Week 2 (Base): defensive footwork and finishing tired', 45, '[{"type":"drill","slug":"lane-slides"},{"type":"drill","slug":"full-court-dribble-sprints"},{"type":"drill","slug":"up-and-under","note":"Finish these moves tired, right after the sprints"},{"type":"exercise","name":"Tibialis Raises","sets":3,"reps":"15"},{"type":"exercise","name":"Couch Stretch (Hip Flexor / Quad)","sets":2,"reps":"60 sec each"},{"type":"study","topic_slug":"defense-rotations"}]'),
  ('big-development', 3, 1, 'Post Moves and Lower Strength', 'Week 3 (Build): post footwork and finishing + leg strength', 50, '[{"type":"drill","slug":"mikan-drill"},{"type":"drill","slug":"up-and-under"},{"type":"drill","slug":"drop-step-series"},{"type":"exercise","name":"Barbell Back Squat","sets":4,"reps":"6"},{"type":"exercise","name":"Barbell Hip Thrust","sets":4,"reps":"8"},{"type":"exercise","name":"Suitcase Carry","sets":3,"reps":"30 m each"}]'),
  ('big-development', 3, 2, 'Rebounding and Touch', 'Week 3 (Build): secure the ball and finish soft + upper strength', 50, '[{"type":"drill","slug":"superman-rebounding"},{"type":"drill","slug":"power-layup-series"},{"type":"drill","slug":"elbow-to-elbow-shooting"},{"type":"exercise","name":"Dumbbell Bench Press","sets":4,"reps":"8"},{"type":"exercise","name":"Chin-Ups","sets":3,"reps":"6"},{"type":"study","topic_slug":"rebounding"}]'),
  ('big-development', 3, 3, 'Face-Up Game and Power', 'Week 3 (Build): face-up moves and shooting range + plyometrics', 50, '[{"type":"drill","slug":"jab-series"},{"type":"drill","slug":"shot-fake-one-dribble"},{"type":"drill","slug":"free-throw-routine-builder"},{"type":"exercise","name":"Broad Jump","sets":4,"reps":"3"},{"type":"exercise","name":"Dead Bug (Contralateral)","sets":3,"reps":"10 each"}]'),
  ('big-development', 3, 4, 'Defense and Conditioning', 'Week 3 (Build): defensive footwork and finishing tired', 35, '[{"type":"drill","slug":"help-and-recover"},{"type":"drill","slug":"sprint-backpedal-transitions"},{"type":"drill","slug":"jump-hook","note":"Finish these moves tired, right after the sprints"},{"type":"exercise","name":"Ankle Dorsiflexion Knee-to-Wall","sets":2,"reps":"10 each"},{"type":"exercise","name":"Deep Squat Hold","sets":2,"reps":"60 sec"}]'),
  ('big-development', 4, 1, 'Post Moves and Lower Strength', 'Week 4 (Build): post footwork and finishing + leg strength', 45, '[{"type":"drill","slug":"two-ball-mikan"},{"type":"drill","slug":"post-face-up-series"},{"type":"drill","slug":"up-and-under"},{"type":"exercise","name":"Barbell Back Squat","sets":4,"reps":"5"},{"type":"exercise","name":"Bulgarian Split Squat","sets":3,"reps":"8 each"},{"type":"exercise","name":"Suitcase Carry","sets":3,"reps":"40 m each"}]'),
  ('big-development', 4, 2, 'Rebounding and Touch', 'Week 4 (Build): secure the ball and finish soft + upper strength', 45, '[{"type":"drill","slug":"superman-rebounding"},{"type":"drill","slug":"inside-hand-finishes"},{"type":"drill","slug":"five-spot-midrange"},{"type":"exercise","name":"Incline Dumbbell Press","sets":4,"reps":"8"},{"type":"exercise","name":"Neutral Grip Pull-Ups","sets":3,"reps":"6"}]'),
  ('big-development', 4, 3, 'Face-Up Game and Power', 'Week 4 (Build): face-up moves and shooting range + plyometrics', 45, '[{"type":"drill","slug":"jab-series"},{"type":"drill","slug":"one-dribble-pull-up"},{"type":"drill","slug":"ten-in-a-row-free-throws"},{"type":"exercise","name":"Rim Touches","sets":3,"reps":"8"},{"type":"exercise","name":"Ab Wheel Rollout","sets":3,"reps":"8"}]'),
  ('big-development', 4, 4, 'Defense and Conditioning', 'Week 4 (Build): defensive footwork and finishing tired', 45, '[{"type":"drill","slug":"slide-turn-sprint"},{"type":"drill","slug":"full-court-layup-challenge"},{"type":"drill","slug":"drop-step-series","note":"Finish these moves tired, right after the sprints"},{"type":"exercise","name":"Single-Leg Calf Raises","sets":3,"reps":"12 each"},{"type":"exercise","name":"90/90 Hip Switches","sets":2,"reps":"6 each side"},{"type":"study","topic_slug":"pnr-reads"}]'),
  ('big-development', 5, 1, 'Post Moves and Lower Strength', 'Week 5 (Game speed): post footwork and finishing + leg strength', 50, '[{"type":"drill","slug":"reverse-mikan"},{"type":"drill","slug":"counter-move-series"},{"type":"drill","slug":"jump-hook"},{"type":"exercise","name":"Trap Bar Deadlift","sets":4,"reps":"4"},{"type":"exercise","name":"Bulgarian Split Squat","sets":4,"reps":"6 each"},{"type":"exercise","name":"Sled Push","sets":4,"reps":"20 m"}]'),
  ('big-development', 5, 2, 'Rebounding and Touch', 'Week 5 (Game speed): secure the ball and finish soft + upper strength', 55, '[{"type":"drill","slug":"putback-series"},{"type":"drill","slug":"off-foot-layups"},{"type":"drill","slug":"elbow-to-elbow-shooting"},{"type":"exercise","name":"Barbell Bench Press","sets":4,"reps":"5"},{"type":"exercise","name":"Pull-Ups","sets":4,"reps":"5"},{"type":"study","topic_slug":"film-study"}]'),
  ('big-development', 5, 3, 'Face-Up Game and Power', 'Week 5 (Game speed): face-up moves and shooting range + plyometrics', 45, '[{"type":"drill","slug":"catch-and-face-up"},{"type":"drill","slug":"one-dribble-pull-up"},{"type":"drill","slug":"tired-legs-free-throws"},{"type":"exercise","name":"Depth Jumps","sets":3,"reps":"4"},{"type":"exercise","name":"Medicine Ball Rotational Scoop Toss","sets":3,"reps":"6 each"}]'),
  ('big-development', 5, 4, 'Defense and Conditioning', 'Week 5 (Game speed): defensive footwork and finishing tired', 40, '[{"type":"drill","slug":"help-and-recover"},{"type":"drill","slug":"line-drills"},{"type":"drill","slug":"post-face-up-series","note":"Finish these moves tired, right after the sprints"},{"type":"exercise","name":"Eccentric Heel Drops","sets":3,"reps":"12"},{"type":"exercise","name":"Couch Stretch (Hip Flexor / Quad)","sets":2,"reps":"60 sec each"}]'),
  ('big-development', 6, 1, 'Post Moves and Lower Strength', 'Week 6 (Game speed): post footwork and finishing + leg strength', 45, '[{"type":"drill","slug":"two-ball-mikan"},{"type":"drill","slug":"counter-move-series"},{"type":"drill","slug":"up-and-under"},{"type":"exercise","name":"Trap Bar Deadlift","sets":3,"reps":"3"},{"type":"exercise","name":"Bulgarian Split Squat","sets":3,"reps":"6 each"},{"type":"exercise","name":"Sled Push","sets":3,"reps":"20 m"}]'),
  ('big-development', 6, 2, 'Rebounding and Touch', 'Week 6 (Game speed): secure the ball and finish soft + upper strength', 45, '[{"type":"drill","slug":"putback-series"},{"type":"drill","slug":"inside-hand-finishes"},{"type":"drill","slug":"five-spot-midrange"},{"type":"exercise","name":"Barbell Bench Press","sets":3,"reps":"5"},{"type":"exercise","name":"Pull-Ups","sets":3,"reps":"5"}]'),
  ('big-development', 6, 3, 'Face-Up Game and Power', 'Week 6 (Game speed): face-up moves and shooting range + plyometrics', 45, '[{"type":"drill","slug":"shot-fake-sweep"},{"type":"drill","slug":"corner-three-series"},{"type":"drill","slug":"free-throw-pressure-ladder"},{"type":"exercise","name":"Approach Vertical Jump","sets":3,"reps":"3"},{"type":"exercise","name":"Pallof Press","sets":3,"reps":"10 each"}]'),
  ('big-development', 6, 4, 'Defense and Conditioning', 'Week 6 (Game speed): defensive footwork and finishing tired', 50, '[{"type":"test","test_type":"standing_vertical"},{"type":"drill","slug":"closeout-sprint-series"},{"type":"drill","slug":"full-court-layup-challenge"},{"type":"drill","slug":"counter-move-series","note":"Finish these moves tired, right after the sprints"},{"type":"exercise","name":"Single-Leg Calf Raises","sets":2,"reps":"12 each"},{"type":"exercise","name":"Deep Squat Hold","sets":2,"reps":"60 sec"},{"type":"study","topic_slug":"mental-game"}]'),
  ('in-season-maintenance', 1, 1, 'Sharpen and Strengthen', 'Week 1: shooting rhythm + light strength', 45, '[{"type":"drill","slug":"form-shooting-one-hand","note":"Quick 25 makes"},{"type":"drill","slug":"five-spot-midrange"},{"type":"drill","slug":"free-throw-routine-builder"},{"type":"exercise","name":"Trap Bar Deadlift","sets":2,"reps":"5"},{"type":"exercise","name":"Pallof Press","sets":2,"reps":"10 each"},{"type":"exercise","name":"Couch Stretch (Hip Flexor / Quad)","sets":2,"reps":"60 sec each"}]'),
  ('in-season-maintenance', 1, 2, 'Game Prep and Recovery', 'Week 1: touch, handle and film', 40, '[{"type":"drill","slug":"pound-dribble-series"},{"type":"drill","slug":"mikan-drill"},{"type":"drill","slug":"spin-out-catch-and-shoot"},{"type":"exercise","name":"World''s Greatest Stretch","sets":2,"reps":"5 each side"},{"type":"study","topic_slug":"film-study"}]'),
  ('in-season-maintenance', 2, 1, 'Sharpen and Strengthen', 'Week 2: shots off the move + single-leg strength', 45, '[{"type":"drill","slug":"form-shooting-ladder"},{"type":"drill","slug":"elbow-to-elbow-shooting"},{"type":"drill","slug":"ten-in-a-row-free-throws"},{"type":"exercise","name":"Bulgarian Split Squat","sets":2,"reps":"6 each"},{"type":"exercise","name":"Pogo Hops","sets":2,"reps":"15"},{"type":"exercise","name":"Dead Bug (Contralateral)","sets":2,"reps":"8 each"}]'),
  ('in-season-maintenance', 2, 2, 'Game Prep and Recovery', 'Week 2: quick hands and mental reps', 40, '[{"type":"drill","slug":"stationary-crossover"},{"type":"drill","slug":"weak-hand-layups"},{"type":"drill","slug":"five-spot-midrange"},{"type":"exercise","name":"Thoracic Spine Rotations (Open Books)","sets":2,"reps":"8 each"},{"type":"study","topic_slug":"mental-game"}]'),
  ('in-season-maintenance', 3, 1, 'Sharpen and Strengthen', 'Week 3: game shots + hamstring health', 45, '[{"type":"drill","slug":"form-shooting-one-hand"},{"type":"drill","slug":"shot-fake-one-dribble","note":"Newer players: use Spin-Out Catch and Shoot"},{"type":"drill","slug":"tired-legs-free-throws"},{"type":"exercise","name":"Trap Bar Deadlift","sets":2,"reps":"4"},{"type":"exercise","name":"Nordic Hamstring Curl","sets":2,"reps":"4"},{"type":"exercise","name":"90/90 Hip Switches","sets":2,"reps":"6 each side"}]'),
  ('in-season-maintenance', 3, 2, 'Game Prep and Recovery', 'Week 3: finishing touch and late-game situations', 40, '[{"type":"drill","slug":"figure-eight-dribble"},{"type":"drill","slug":"reverse-mikan"},{"type":"drill","slug":"around-the-world"},{"type":"exercise","name":"Ankle Dorsiflexion Knee-to-Wall","sets":2,"reps":"10 each"},{"type":"study","topic_slug":"game-situations"}]'),
  ('in-season-maintenance', 4, 1, 'Sharpen and Strengthen', 'Week 4: stay sharp + stay springy', 45, '[{"type":"drill","slug":"form-shooting-ladder"},{"type":"drill","slug":"spin-out-catch-and-shoot"},{"type":"drill","slug":"ten-in-a-row-free-throws"},{"type":"exercise","name":"Goblet Squat","sets":2,"reps":"8"},{"type":"exercise","name":"Box Jumps","sets":2,"reps":"3"},{"type":"exercise","name":"Thoracic Spine Rotations (Open Books)","sets":2,"reps":"8 each"}]'),
  ('in-season-maintenance', 4, 2, 'Game Prep and Recovery', 'Week 4: rhythm and defensive IQ', 40, '[{"type":"drill","slug":"pound-dribble-series"},{"type":"drill","slug":"mikan-drill"},{"type":"drill","slug":"five-spot-midrange"},{"type":"exercise","name":"World''s Greatest Stretch","sets":2,"reps":"5 each side"},{"type":"study","topic_slug":"defense-rotations"},{"type":"note","text":"Skip this session the day before a game if your legs feel heavy."}]'),
  ('beginner-complete', 1, 1, 'Ball Control and Form', 'Week 1: dribble with your fingertips, shoot with one hand', 30, '[{"type":"drill","slug":"pound-dribble-series"},{"type":"drill","slug":"ball-wraps"},{"type":"drill","slug":"form-shooting-one-hand"},{"type":"exercise","name":"Goblet Squat","sets":2,"reps":"10"},{"type":"exercise","name":"Front Plank","sets":2,"reps":"20 sec"}]'),
  ('beginner-complete', 1, 2, 'Footwork and Layups', 'Week 1: balance, jump stops and basic layups', 30, '[{"type":"drill","slug":"triple-threat-stance"},{"type":"drill","slug":"jump-stop-landings"},{"type":"drill","slug":"power-layup-series"},{"type":"exercise","name":"Glute Bridge","sets":2,"reps":"12"},{"type":"exercise","name":"Jump Rope","sets":3,"reps":"30 sec"}]'),
  ('beginner-complete', 1, 3, 'Defense and Free Throws', 'Week 1: defensive stance and a free-throw routine', 45, '[{"type":"drill","slug":"defensive-stance-holds"},{"type":"drill","slug":"lane-slides"},{"type":"drill","slug":"free-throw-routine-builder"},{"type":"exercise","name":"Push-Ups (Tempo)","sets":2,"reps":"6"},{"type":"exercise","name":"Bird Dog","sets":2,"reps":"6 each"},{"type":"study","topic_slug":"shooting-mechanics"}]'),
  ('beginner-complete', 2, 1, 'Handle and Shot Range', 'Week 2: crossovers and form shooting ladder', 35, '[{"type":"drill","slug":"figure-eight-dribble"},{"type":"drill","slug":"stationary-crossover"},{"type":"drill","slug":"form-shooting-ladder"},{"type":"exercise","name":"Reverse Lunge","sets":2,"reps":"8 each"},{"type":"exercise","name":"Side Plank","sets":2,"reps":"15 sec each"}]'),
  ('beginner-complete', 2, 2, 'Pivots and Weak-Hand Layups', 'Week 2: pivoting and finishing with both hands', 40, '[{"type":"drill","slug":"pivot-series"},{"type":"drill","slug":"one-two-step-vs-hop"},{"type":"drill","slug":"weak-hand-layups"},{"type":"drill","slug":"mikan-drill"},{"type":"exercise","name":"Pogo Hops","sets":2,"reps":"15"},{"type":"exercise","name":"Dead Bug (Contralateral)","sets":2,"reps":"6 each"}]'),
  ('beginner-complete', 2, 3, 'Defense, Rebounding and Shooting', 'Week 2: slides, securing rebounds and catch-and-shoot', 45, '[{"type":"drill","slug":"zig-zag-slides","note":"No cones? Use shoes or water bottles."},{"type":"drill","slug":"toss-rebound-chin"},{"type":"drill","slug":"spin-out-catch-and-shoot"},{"type":"exercise","name":"Inverted Row","sets":2,"reps":"8"},{"type":"exercise","name":"Lateral Band Walk","sets":2,"reps":"10 each way"},{"type":"study","topic_slug":"ball-handling"}]'),
  ('beginner-complete', 3, 1, 'Dribble on the Move', 'Week 3: dribble moves and elbow shooting', 40, '[{"type":"drill","slug":"v-dribble"},{"type":"drill","slug":"between-legs-stationary"},{"type":"drill","slug":"full-court-speed-dribble"},{"type":"drill","slug":"elbow-to-elbow-shooting"},{"type":"exercise","name":"Goblet Squat","sets":3,"reps":"8"},{"type":"exercise","name":"Front Plank","sets":3,"reps":"30 sec"}]'),
  ('beginner-complete', 3, 2, 'Finishing Variety', 'Week 3: jump stops, reverse layups and footwork shooting', 40, '[{"type":"drill","slug":"jump-stop-finishes"},{"type":"drill","slug":"baseline-reverse-layups"},{"type":"drill","slug":"hop-vs-one-two-shooting"},{"type":"exercise","name":"Glute Bridge","sets":3,"reps":"12"},{"type":"exercise","name":"Single-Leg Balance Reach","sets":2,"reps":"6 each"}]'),
  ('beginner-complete', 3, 3, 'Closeouts, Passing and Midrange', 'Week 3: close out under control and pass on target', 55, '[{"type":"drill","slug":"closeout-fundamentals","note":"No cones? Use shoes or water bottles."},{"type":"drill","slug":"backboard-tips"},{"type":"drill","slug":"wall-chest-passes"},{"type":"drill","slug":"five-spot-midrange"},{"type":"exercise","name":"Push-Ups (Tempo)","sets":3,"reps":"8"},{"type":"exercise","name":"Jump Rope","sets":3,"reps":"45 sec"},{"type":"study","topic_slug":"finishing-footwork"}]'),
  ('beginner-complete', 4, 1, 'Weak Hand and Shooting Game', 'Week 4: weak-hand control and Around the World', 40, '[{"type":"drill","slug":"weak-hand-stationary"},{"type":"drill","slug":"two-ball-pound"},{"type":"drill","slug":"around-the-world"},{"type":"exercise","name":"Reverse Lunge","sets":3,"reps":"8 each"},{"type":"exercise","name":"Side Plank","sets":3,"reps":"20 sec each"}]'),
  ('beginner-complete', 4, 2, 'Layup Mastery', 'Week 4: finish with both hands and different layups', 45, '[{"type":"drill","slug":"mikan-drill"},{"type":"drill","slug":"weak-hand-layups"},{"type":"drill","slug":"scoop-layup"},{"type":"drill","slug":"spin-out-catch-and-shoot"},{"type":"exercise","name":"Box Jumps","sets":3,"reps":"3"},{"type":"exercise","name":"Bird Dog","sets":3,"reps":"8 each"}]'),
  ('beginner-complete', 4, 3, 'Put It All Together', 'Week 4: full workout and check your progress', 60, '[{"type":"drill","slug":"full-court-dribble-sprints"},{"type":"drill","slug":"lane-line-touches"},{"type":"drill","slug":"bank-shot-series"},{"type":"drill","slug":"free-throw-routine-builder","note":"Count makes out of 20 and compare with week 1"},{"type":"exercise","name":"Pogo Hops","sets":3,"reps":"20"},{"type":"exercise","name":"Dead Bug (Contralateral)","sets":3,"reps":"8 each"},{"type":"study","topic_slug":"spacing-off-ball"}]')
) AS v(slug, week, day, title, focus, estimated_minutes, items)
JOIN public.training_programs p ON p.slug = v.slug
ON CONFLICT (program_id, week, day) DO NOTHING;
